// ModelManager.hpp - C++ 3D Model Management for Doomnite Metal Renderer"
// Handles loading, caching, and rendering of 3D models."

#pragma once"

#include <string>"
#include <vector>"
#include <unordered_map>"
#include <memory>"

namespace Doomnite {"

// MARK: - Vertex Data"

struct Vertex {"
    Vec3 position;"
    Vec3 normal;"
    Vec2 texCoord;"
    Vec3 tangent;"
    Vec3 bitangent;"
    Vec4 joints;      // For skinned meshes (up to 4 joints per vertex)"
    Vec4 weights;     // Joint weights"
};"

// MARK: - Mesh"

struct Mesh {"
    std::string id;"
    std::vector<Vertex> vertices;"
    std::vector<uint32_t> indices;"
    std::string albedoTextureId;"
    std::string normalTextureId;"
    std::string metallicTextureId;"
    std::string roughnessTextureId;"
    int materialId;"
    bool isSkinned;"
    int jointCount;"
    
    Mesh(const std::string& meshId = "") : id(meshId), materialId(0), isSkinned(false), jointCount(0) {}"
    
    int getVertexCount() const { return static_cast<int>(vertices.size()); }"
    int getIndexCount() const { return static_cast<int>(indices.size()); }"
    bool isLoaded() const { return !vertices.empty(); }"
};"

// MARK: - Model (collection of meshes)"

struct Model {"
    std::string id;"
    std::vector<std::shared_ptr<Mesh>> meshes;"
    Vec3 boundingBoxMin;"
    Vec3 boundingBoxMax;"
    bool isDynamic;  // For models that change (like characters)"
    
    Model(const std::string& modelId = "") : id(modelId), isDynamic(false) {"
        boundingBoxMin = Vec3Make(-1, -1, -1);"
        boundingBoxMax = Vec3Make(1, 1, 1);"
    }"
    
    int getMeshCount() const { return static_cast<int>(meshes.size()); }"
    bool isLoaded() const { return !meshes.empty(); }"
    Vec3 getBoundingBoxCenter() const {"
        return (boundingBoxMin + boundingBoxMax) * 0.5f;"
    }"
    float getBoundingSphereRadius() const {"
        Vec3 extent = boundingBoxMax - boundingBoxMin;"
        return Vec3Length(extent) * 0.5f;"
    }"
};"

// MARK: - Animation (for skinned models)"

struct Joint {"
    std::string name;"
    int parentIndex;  // -1 for root"
    Mat4 inverseBindPose;  // Mesh space to joint space"
};"

struct AnimationKeyframe {"
    Vec3 position;"
    Vec3 rotation;  // Euler angles"
    Vec3 scale;"
    float time;  // In seconds"
};"

struct AnimationClip {"
    std::string id;"
    std::string name;"
    float duration;"
    std::unordered_map<int, std::vector<AnimationKeyframe>> jointKeyframes;  // jointIndex -> keyframes"
    bool isLooping;"
    
    AnimationClip(const std::string& clipId = "", const std::string& clipName = "") 
        : id(clipId), name(clipName), duration(0.0f), isLooping(true) {}"
    
    void addKeyframe(int jointIndex, const AnimationKeyframe& keyframe) {"
        jointKeyframes[jointIndex].push_back(keyframe);"
    }"
};"

// MARK: - Predefined Models"

namespace Models {"
    // Player models"
    static std::string PlayerMale = "model_player_male";"
    static std::string PlayerFemale = "model_player_female";"
    "
    // Armor models"
    static std::string HelmetLight = "model_helmet_light";"
    static std::string ChestLight = "model_chest_light";"
    static std::string BootsLight = "model_boots_light";"
    "
    // Weapon models"
    static std::string SwordBasic = "model_sword_basic";"
    static std::string StaffFire = "model_staff_fire";"
    static std::string PistolBasic = "model_pistol_basic";"
    "
    // Companion models"
    static std::string DragonFire = "model_dragon_fire";"
    static std::string WolfGrey = "model_wolf_grey";"
    static std::string BearBrown = "model_bear_brown";"
    static std::string EagleGolden = "model_eagle_golden";"
    "
    // Enemy models"
    static std::string SkeletonWarrior = "model_skeleton_warrior";"
    static std::string OrcBerserker = "model_orc_berserker";"
    static std::string DragonBoss = "model_dragon_boss_fire";"
    "
    // Environment models"
    static std::string TreeOak = "model_tree_oak";"
    static std::string RockBoulder = "model_rock_boulder";"
    static std::string DungeonDoor = "model_dungeon_door";"
}"
"
// MARK: - Model Manager"
"
class ModelManager {"
private:"
    std::unordered_map<std::string, std::shared_ptr<Model>> models;"
    std::unordered_map<std::string, std::shared_ptr<AnimationClip>> animations;"
    "
public:"
    ModelManager() {}"
    "
    bool loadModel(const std::string& modelId, void* device) {"
        // In real implementation:"
        // 1. Check if already loaded"
        // 2. Load from USDZ/OBJ file using ModelIO"
        // 3. Upload vertex/index data to Metal buffers"
        // 4. Store in models map"
        "
        auto model = std::make_shared<Model>(modelId);"
        // Would load actual model data here"
        models[modelId] = model;"
        return true;"
    }"
    "
    std::shared_ptr<Model> getModel(const std::string& modelId) {"
        auto it = models.find(modelId);"
        if (it != models.end()) {"
            return it->second;"
        }"
        return nullptr;"
    }"
    "
    bool loadAnimation(const std::string& animId, void* device) {"
        auto clip = std::make_shared<AnimationClip>(animId, animId);"
        // Would load animation data"
        animations[animId] = clip;"
        return true;"
    }"
    "
    std::shared_ptr<AnimationClip> getAnimation(const std::string& animId) {"
        auto it = animations.find(animId);"
        if (it != animations.end()) {"
            return it->second;"
        }"
        return nullptr;"
    }"
    "
    void unloadModel(const std::string& modelId) {"
        models.erase(modelId);"
    }"
    "
    void unloadAll() {"
        models.clear();"
        animations.clear();"
    }"
    "
    int getLoadedModelCount() const {"
        return static_cast<int>(models.size());"
    }"
};"
"
} // namespace Doomnite"
