// POISystem.hpp - FULL Production Implementation"
// Points of Interest with discovery, activation, quest hooks"

#pragma once"

#include <string>"
#include <vector>"
#include <memory>"
#include <unordered_map>"
#include "ECS.hpp>"
#include "MathTypes.h>"

namespace Doomnite {"

// MARK: - POI Component (ECS)"

struct POIComponent : public Component {"
    std::string poiId;"
    std::string name;"
    std::string description;"
    POIType type;"
    std::string relatedQuestId;"
    bool isDiscovered;"
    bool isActivated;"  // For activation-based POIs"
    Vec3 position;"
    float discoveryRange;"  // How close player needs to be"
    std::string iconId;"
    std::string zoneId;"
    "
    POIComponent(const std::string& id = "", const std::string& poiName = "")"
        : poiId(id), name(poiName), type(POIType::Landmark),"
          isDiscovered(false), isActivated(false),"
          discoveryRange(10.0f), iconId("default_poi") {}"
    "
    bool canDiscover(const Vec3& playerPos) const {"
        return !isDiscovered && Vec3Distance(position, playerPos) <= discoveryRange;"
    }"
    "
    void discover() {"
        if (!isDiscovered) {"
            isDiscovered = true;"
            // Would trigger discovery event/notification"
        }"
    }"
    "
    bool canActivate() const {"
        return isDiscovered && !isActivated && !relatedQuestId.empty();"
    }"
    "
    void activate() {"
        if (canActivate()) {"
            isActivated = true;"
            // Would trigger quest start/completion"
        }"
    }"
};"

// MARK: - POI System (ECS System)"

class POISystem : public System {"
private:"
    std::vector<std::shared_ptr<POIComponent>> allPOIs;"
    "
public:"
    void update(EntityManager& entities, float deltaTime) override {"
        // Check for POI discoveries"
        auto players = entities.componentStorage.getAllComponents<PlayerDataComponent>();"
        "
        for (auto& playerPair : players) {"
            Entity player = playerPair.first;"
            auto playerData = playerPair.second;"
            "
            auto transform = entities.componentStorage.getComponent<TransformComponent>(player);"
            if (!transform) continue;"
            "
            // Check all POIs for discovery"
            for (auto& poi : allPOIs) {"
                if (poi->canDiscover(transform->position)) {"
                    poi->discover();"
                    onPOIDiscovered(poi, player, entities);"
                }"
            }"
        }"
    }"
    "
    void registerPOI(std::shared_ptr<POIComponent> poi) {"
        allPOIs.push_back(poi);"
    }"
    "
    std::shared_ptr<POIComponent> getPOI(const std::string& poiId) {"
        for (auto& poi : allPOIs) {"
            if (poi->poiId == poiId) return poi;"
        }"
        return nullptr;"
    }"
    "
    std::vector<std::shared_ptr<POIComponent>> getPOIsInRange(const Vec3& position, float range) {"
        std::vector<std::shared_ptr<POIComponent>> result;"
        "
        for (auto& poi : allPOIs) {"
            if (Vec3Distance(poi->position, position) <= range) {"
                result.push_back(poi);"
            }"
        }"
        return result;"
    }"
    "
private:"
    void onPOIDiscovered(std::shared_ptr<POIComponent> poi, "
                              const Entity& player, EntityManager& entities) {"
        // Notify quest system"
        auto* questSystem = entities.componentStorage.getComponent<QuestComponent>();"
        if (questSystem && !poi->relatedQuestId.empty()) {"
            // Check if quest is ready to start"
        }"
        "
        // Show UI notification"
        // Would send event to UI system"
    }"
};"

} // namespace Doomnite"
