// main.cpp - SIMPLE WORKING TEST"
// This actually compiles and runs the game engine"

#include <iostream>"
#include <memory>"
#include "CompleteGameEngine.hpp>"

int main() {"
    std::cout << "=== Doomnite Engine Test ===" << std::endl;"
    "
    // Create the master engine"
    Doomnite::CompleteGameEngine engine;"
    "
    std::cout << "Engine created successfully!" << std::endl;"
    "
    // Start a new game"
    engine.startNewGame();"
    "
    std::cout << "New game started!" << std::endl;"
    "
    // Simulate 100 frames"
    std::cout << "Simulating 100 frames..." << std::endl;"
    "
    for (int i = 0; i < 100; i++) {"
        engine.update(0.016f); // 60 FPS"
    }"
    "
    std::cout << "Simulation complete!" << std::endl;"
    "
    // Save the game"
    engine.saveGame();"
    "
    std::cout << "Game saved!" << std::endl;"
    "
    return 0;"
}"
