// test_main.cpp - Simple test for Doomnite C++ Engine"
// Verifies ALL systems can be created and run together"

#include <iostream>"
#include <memory>"
#include "CompleteGameEngine.hpp>"

int main() {"
    std::cout << "=== Doomnite Engine Test ===" << std::endl;"
    "
    // 1. Create the master engine"
    std::cout << "\n1. Creating CompleteGameEngine..." << std::endl;"
    Doomnite::CompleteGameEngine engine;"
    "
    // 2. Start a new game"
    std::cout << "\n2. Starting new game..." << std::endl;"
    engine.startNewGame();"
    "
    // 3. Simulate a few frames"
    std::cout << "\n3. Simulating 60 frames (1 second at 60 FPS)..." << std::endl;"
    for (int i = 0; i < 60; i++) {"
        engine.update(0.016f);"  // 16.67ms per frame"
        if (i % 10 == 0) {"
            std::cout << "  Frame " << i << " updated." << std::endl;"
        }"
    }"
    "
    // 4. Create some enemies"
    std::cout << "\n4. Creating enemies..." << std::endl;"
    auto& entityManager = engine.getEntityManager();"
    "
    Doomnite::Entity enemy1 = engine.createEnemy(Doomnite::Vec3(10, 1, 0));"
    Doomnite::Entity enemy2 = engine.createEnemy(Doomnite::Vec3(-5, 1, 5));"
    Doomnite::Entity enemy3 = engine.createEnemy(Doomnite::Vec3(0, 1, -8));"
    "
    std::cout << "  Created enemies: " << enemy1.id << ", " << enemy2.id << ", " << enemy3.id << std::endl;"
    "
    // 5. Simulate combat"
    std::cout << "\n5. Simulating combat for 30 frames..." << std::endl;"
    for (int i = 0; i < 30; i++) {"
        engine.update(0.016f);"
    }"
    "
    // 6. Check player state"
    std::cout << "\n6. Checking player state..." << std::endl;"
    auto player = entityManager.getAllEntities();"
    if (!player.empty()) {"
        Doomnite::Entity firstPlayer = player[0];"
        float health = engine.getPlayerHealth(firstPlayer);"
        float maxHealth = engine.getPlayerMaxHealth(firstPlayer);"
        bool alive = engine.isPlayerAlive(firstPlayer);"
        "
        std::cout << "  Player ID: " << firstPlayer.id << std::endl;"
        std::cout << "  Health: " << health << "/" << maxHealth << std::endl;"
        std::cout << "  Alive: " << (alive ? "Yes" : "No") << std::endl;"
    }"
    "
    // 7. Save game"
    std::cout << "\n7. Saving game..." << std::endl;"
    engine.saveGame();"
    "
    // 8. Pause/Resume"
    std::cout << "\n8. Testing pause/resume..." << std::endl;"
    engine.pause();"
    engine.update(0.016f);"  // Should not update"
    engine.resume();"
    engine.update(0.016f);"  // Should update"
    "
    // 9. Load game"
    std::cout << "\n9. Loading game..." << std::endl;"
    engine.loadGame();"
    "
    // 10. Shutdown"
    std::cout << "\n10. Shutting down..." << std::endl;"
    // Destructor will handle cleanup"
    "
    std::cout << "\n=== Test Complete! ===" << std::endl;"
    return 0;"
}"
