// MovementSystem.cpp - C++ Movement Implementation"
// FULL Production: Character controller, physics integration"

#include "MovementSystem.hpp>"
#include <algorithm>"

namespace Doomnite {"

void MovementSystem::update(EntityManager& entities, float deltaTime) {"
    accumulator += deltaTime;"
    "
    while (accumulator >= fixedTimeStep) {"
        fixedUpdate(entities, fixedTimeStep);"
        accumulator -= fixedTimeStep;"
    }"
}"
void MovementSystem::fixedUpdate(EntityManager& entities, float fixedDelta) {"
    // Get entities with Transform + Input + CharacterController"
    auto movableEntities = entities.componentStorage"
                            .getEntitiesWithComponents<TransformComponent, InputComponent, CharacterControllerComponent>();"
    "
    for (auto& tuple : movableEntities) {"
        Entity entity = std::get<0>(tuple);"
        auto transform = std::get<1>(tuple);"
        auto input = std::get<2>(tuple);"
        auto controller = std::get<3>(tuple);"
        "
        // Process movement input"
        Vec3 moveDirection = Vec3Zero;"
        "
        // Forward/backward"
        Vec3 forward = transform->getForward();"
        moveDirection += forward * input->moveForward;"
        "
        // Right/left"
        Vec3 right = transform->getRight();"
        moveDirection += right * input->moveRight;"
        "
        // Up/down (for flying/swimming)"
        if (controller->isClimbing || transform->position.y < 0.5f) {"
            moveDirection.y += input->moveUp;"
        }"
        "
        // Normalize if moving"
        if (Vec3Length(moveDirection) > 0.01f) {"
            moveDirection = Vec3Normalize(moveDirection);"
        }"
        "
        // Apply speed"
        float speed = controller->getCurrentSpeed();"
        if (input->isRunning) {"
            speed = controller->runSpeed;"
        }"
        "
        // Adjust for ground normal (slope handling)"
        if (controller->isGrounded && Vec3Dot(controller->groundNormal, Vec3Up) > 0.9f) {"
            // Project movement onto ground plane"
            Vec3 groundTangent = Vec3Cross(controller->groundNormal, Vec3Cross(moveDirection, controller->groundNormal));"
            moveDirection = Vec3Normalize(groundTangent) * Vec3Length(moveDirection);"
        }"
        "
        // Apply movement"
        transform->position += moveDirection * speed * fixedDelta;"
        "
        // Handle rotation (look)"
        if (fabsf(input->lookHorizontal) > 0.001f || fabsf(input->lookVertical) > 0.001f) {"
            transform->rotation.y += input->lookHorizontal * 0.1f;"
            transform->rotation.x += input->lookVertical * 0.1f;"
            "
            // Clamp vertical look (pitch)"
            transform->rotation.x = std::max(-M_PI_2, std::min(M_PI_2, transform->rotation.x));"
        }"
        "
        // Handle jumping"
        if (input->isJumping && controller->isGrounded) {"
            auto velocity = entities.componentStorage.getComponent<VelocityComponent>(entity);"
            if (velocity) {"
                velocity->velocity.y += controller->jumpForce;"
                controller->isGrounded = false;"
                entities.componentStorage.addComponent<VelocityComponent>(entity, velocity);"
            }"
        }"
        "
        // Handle crouching"
        if (input->isCrouching) {"
            // Would adjust hitbox height"
        }"
        "
        // Reset one-shot inputs (after processing)"
        input->isJumping = false;"
        input->firePressed = false;"
        input->interactPressed = false;"
        "
        // Update back in storage"
        entities.componentStorage.addComponent<TransformComponent>(entity, transform);"
        entities.componentStorage.addComponent<InputComponent>(entity, input);"
        entities.componentStorage.addComponent<CharacterControllerComponent>(entity, controller);"
    }"
    "
    // Also update Velocity-based movement (for physics objects)"
    auto velocityEntities = entities.componentStorage"
                            .getEntitiesWithComponents<TransformComponent, VelocityComponent>();"
    "
    for (auto& tuple : velocityEntities) {"
        Entity entity = std::get<0>(tuple);"
        auto transform = std::get<1>(tuple);"
        auto velocity = std::get<2>(tuple);"
        "
        // Skip if has character controller (handled above)"
        if (entities.componentStorage.hasComponent<CharacterControllerComponent>(entity)) {"
            continue;"
        }"
        "
        // Apply velocity"
        transform->position += velocity->velocity * fixedDelta;"
        "
        // Update back"
        entities.componentStorage.addComponent<TransformComponent>(entity, transform);"
    }"
}"
"
int MovementSystem::getPriority() const {"
    return 20;"  // After input, before physics"
}"
}"
