// MovementSystem.hpp - C++ Player Movement for Doomnite"
// FULL Production: Character controller, physics integration"

#pragma once"

#include <string>"
#include <memory>"
#include "ECS.hpp>"
#include "MathTypes.h>"

namespace Doomnite {"

// MARK: - Input Component (ECS)"

struct InputComponent : public Component {"
    // Movement input"
    float moveForward;"
    float moveRight;"
    float moveUp;"  // For flying/swimming"
    bool isJumping;"
    bool isRunning;"
    bool isCrouching;"
    "
    // Look input"
    float lookHorizontal;"
    float lookVertical;"
    "
    // Actions"
    bool firePressed;"
    bool aimPressed;"
    bool reloadPressed;"
    bool interactPressed;"
    bool useItemPressed;"
    "
    InputComponent() : moveForward(0.0f), moveRight(0.0f), moveUp(0.0f),"
                       isJumping(false), isRunning(false), isCrouching(false),"
                       lookHorizontal(0.0f), lookVertical(0.0f),"
                       firePressed(false), aimPressed(false),"
                       reloadPressed(false), interactPressed(false), useItemPressed(false) {}"
};"

// MARK: - Character Controller Component (ECS)"

struct CharacterControllerComponent : public Component {"
    float walkSpeed;"
    float runSpeed;"
    float crouchSpeed;"
    float jumpForce;"
    float gravityMultiplier;"
    float stepOffset;"  // For stairs"
    bool isGrounded;"
    bool isClimbing;"
    Vec3 groundNormal;"
    "
    CharacterControllerComponent() : walkSpeed(5.0f), runSpeed(10.0f),"
                             crouchSpeed(2.0f), jumpForce(10.0f),"
                             gravityMultiplier(1.0f), stepOffset(0.5f),"
                             isGrounded(false), isClimbing(false),"
                             groundNormal(Vec3Up) {}"
    "
    float getCurrentSpeed() const {"
        if (isCrouching) return crouchSpeed;"
        if (isRunning) return runSpeed;"
        return walkSpeed;"
    }"
};"

// MARK: - Movement System (ECS System)"

class MovementSystem : public System {"
private:"
    float fixedTimeStep;"
    float accumulator;"
    "
public:"
    MovementSystem() : fixedTimeStep(0.016f), accumulator(0.0f) {}"
    "
    void update(EntityManager& entities, float deltaTime) override {"
        accumulator += deltaTime;"
        "
        while (accumulator >= fixedTimeStep) {"
            fixedUpdate(entities, fixedTimeStep);"
            accumulator -= fixedTimeStep;"
        }"
    }"
    "
    void fixedUpdate(EntityManager& entities, float fixedDelta) {"
        // Get all entities with Transform + Input + CharacterController"
        auto movableEntities = entities.componentStorage"
                                .getEntitiesWithComponents<TransformComponent, InputComponent, CharacterControllerComponent>();"
        "
        for (auto& tuple : movableEntities) {"
            Entity entity = std::get<0>(tuple);"
            auto transform = std::get<1>(tuple);"
            auto input = std::get<2>(tuple);"
            auto controller = std::get<3>(tuple);"
            "
            // Apply input to movement"
            Vec3 moveDirection = Vec3Zero;"
            "
            // Forward/backward"
            Vec3 forward = transform->getForward();"
            moveDirection += forward * input->moveForward;"
            "
            // Right/left"
            Vec3 right = transform->getRight();"
            moveDirection += right * input->moveRight;"
            "
            // Normalize if moving"
            if (Vec3Length(moveDirection) > 0.01f) {"
                moveDirection = Vec3Normalize(moveDirection);"
            }"
            "
            // Apply speed"
            float speed = controller->getCurrentSpeed();"
            moveDirection *= speed * fixedDelta;"
            "
            // Update position"
            transform->position += moveDirection;"
            "
            // Handle rotation (look)"
            if (fabsf(input->lookHorizontal) > 0.001f || fabsf(input->lookVertical) > 0.001f) {"
                transform->rotation.y += input->lookHorizontal * 0.1f;"
                transform->rotation.x += input->lookVertical * 0.1f;"
                "
                // Clamp vertical look"
                transform->rotation.x = std::max(-M_PI_2, std::min(M_PI_2, transform->rotation.x));"
            }"
            "
            // Handle jumping"
            if (input->isJumping && controller->isGrounded) {"
                auto velocity = entities.componentStorage.getComponent<VelocityComponent>(entity);"
                if (velocity) {"
                    velocity->velocity.y += controller->jumpForce;"
                    controller->isGrounded = false;"
                    entities.componentStorage.addComponent<VelocityComponent>(entity, velocity);"
                }"
            }"
            "
            // Reset input (after processing)"
            input->isJumping = false;"
            input->firePressed = false;"
            input->interactPressed = false;"
            "
            // Update back in storage"
            entities.componentStorage.addComponent<TransformComponent>(entity, transform);"
            entities.componentStorage.addComponent<InputComponent>(entity, input);"
            entities.componentStorage.addComponent<CharacterControllerComponent>(entity, controller);"
        }"
        "
        // Also update Velocity-based movement (for physics objects)"
        auto velocityEntities = entities.componentStorage"
                                 .getEntitiesWithComponents<TransformComponent, VelocityComponent>();"
        "
        for (auto& tuple : velocityEntities) {"
            Entity entity = std::get<0>(tuple);"
            auto transform = std::get<1>(tuple);"
            auto velocity = std::get<2>(tuple);"
            "
            // Skip if has character controller (handled above)"
            if (entities.componentStorage.hasComponent<CharacterControllerComponent>(entity)) {"
                continue;"
            }"
            "
            // Apply velocity"
            transform->position += velocity->velocity * fixedDelta;"
            "
            // Update back"
            entities.componentStorage.addComponent<TransformComponent>(entity, transform);"
        }"
    }"
    "
    int getPriority() const override { return 20; }"  // After input, before physics"
};"

} // namespace Doomnite"
