// CombatSystem.cpp - C++ Combat System Implementation"
// FULL Production: Damage application, combat logic"

#include "CombatSystem.hpp>"
#include <algorithm>"
#include <iostream>"

namespace Doomnite {"

void CombatSystem::update(EntityManager& entities, float deltaTime) {"
    // Process pending damage"
    for (const auto& damage : pendingDamage) {"
        applyDamage(damage, entities);"
    }"
    pendingDamage.clear();"
    "
    // Update attack timers for all combat entities"
    auto combatComps = entities.componentStorage.getAllComponents<CombatComponent>();"
    "
    for (auto& pair : combatComps) {"
        Entity entity = pair.first;"
        auto combat = pair.second;"
        "
        // Update attack cooldown"
        if (combat->attackTimer > 0.0f) {"
            combat->attackTimer -= deltaTime;"
        }"
        "
        // Check for auto-attack if target exists"
        if (combat->hasTarget() && combat->attackTimer <= 0.0f) {"
            auto targetTransform = entities.componentStorage.getComponent<TransformComponent>(combat->targetEntity);"
            auto entityTransform = entities.componentStorage.getComponent<TransformComponent>(entity);"
            "
            if (targetTransform && entityTransform) {"
                float distance = Vec3Distance(entityTransform->position, targetTransform->position);"
                "
                if (distance <= combat->attackRange) {"
                    // Perform attack"
                    performAttack(entity, combat, entities);"
                    combat->attackTimer = 1.0f / combat->attackSpeed;"
                }"
            }"
        }"
        "
        // Update back in storage"
        entities.componentStorage.addComponent<CombatComponent>(entity, combat);"
    }"
}"
"
void CombatSystem::dealDamage(const DamageInfo& damage, EntityManager& entities) {"
    pendingDamage.push_back(damage);"
}"
"
void CombatSystem::applyDamage(const DamageInfo& damage, EntityManager& entities) {"
    auto health = entities.componentStorage.getComponent<HealthComponent>(damage.victim);"
    auto combat = entities.componentStorage.getComponent<CombatComponent>(damage.victim);"
    "
    if (!health || !health->isAlive) return;"
    "
    // Calculate actual damage"
    float actualDamage = damage.amount;"
    "
    // Apply damage type resistance"
    if (combat) {"
        actualDamage = combat->applyDamageResistance(actualDamage, damage.type);"
    }"
    "
    // Apply armor penetration"
    if (damage.penetration > 0.0f && combat) {"
        // Would reduce effective armor"
    }"
    "
    // Critical hit"
    bool isCritical = damage.isCritical;"
    if (!isCritical && combat) {"
        isCritical = combat->rollCritical();"
    }"
    "
    if (isCritical) {"
        actualDamage *= 1.5f;"  // Simplified critical multiplier"
    }"
    "
    // Apply damage"
    bool wasKilled = health->takeDamage(actualDamage);"
    "
    // Lifesteal"
    if (damage.attacker.id != 0 && combat) {"
        float lifestealAmount = actualDamage * combat->lifesteal;"
        if (lifestealAmount > 0.0f) {"
            auto attackerHealth = entities.componentStorage.getComponent<HealthComponent>(damage.attacker);"
            if (attackerHealth) {"
                attackerHealth->heal(lifestealAmount);"
                entities.componentStorage.addComponent<HealthComponent>(damage.attacker, attackerHealth);"
            }"
        }"
    }"
    "
    // Fire callbacks"
    for (const auto& callback : damageCallbacks) {"
        callback(damage);"
    }"
    "
    // Notify other systems"
    if (wasKilled) {"
        onEntityKilled(damage, entities);"
    }"
    "
    // Update back in storage"
    entities.componentStorage.addComponent<HealthComponent>(damage.victim, health);"
}"
"
void CombatSystem::performAttack(const Entity& attacker, std::shared_ptr<CombatComponent> combat, EntityManager& entities) {"
    // Get attacker position"
    auto attackerTransform = entities.componentStorage.getComponent<TransformComponent>(attacker);"
    if (!attackerTransform) return;"
    "
    // Check if ranged or melee"
    if (combat->attackRange > 3.0f) {"
        // Ranged attack (raycast)"
        Vec3 direction = Vec3Normalize(attackerTransform->getForward());"
        HitResult hit = raycastHit(attackerTransform->position, direction, combat->attackRange, entities, attacker);"
        "
        if (hit.isHit) {"
            DamageInfo damage(combat->getTotalDamage(), DamageType::Physical, attacker, hit.hitEntity);"
            damage.hitPoint = hit.hitPoint;"
            damage.isCritical = combat->rollCritical();"
            dealDamage(damage, entities);"
        }"
    } else {"
        // Melee attack (sphere check)"
        auto hits = meleeHits(attackerTransform->position, combat->attackRange, entities, attacker);"
        "
        for (const auto& hitEntity : hits) {"
            DamageInfo damage(combat->getTotalDamage(), DamageType::Physical, attacker, hitEntity);"
            damage.isCritical = combat->rollCritical();"
            dealDamage(damage, entities);"
        }"
    }"
}"
"
HitResult CombatSystem::raycastHit(const Vec3& origin, const Vec3& direction,"
                                  float maxDistance, EntityManager& entities,"
                                  Entity ignoreEntity) {"
    HitResult result;"
    "
    auto allTransforms = entities.componentStorage.getAllComponents<TransformComponent>();"
    float closestDist = maxDistance;"
    "
    for (const auto& pair : allTransforms) {"
        Entity entity = pair.first;"
        if (entity.id == ignoreEntity.id) continue;"
        "
        auto collider = entities.componentStorage.getComponent<ColliderComponent>(entity);"
        if (!collider) continue;"
        "
        // Simple ray-sphere check"
        auto transform = pair.second;"
        Vec3 toCenter = transform->position - origin;"
        float t = Vec3Dot(toCenter, direction);"
        "
        if (t < 0) continue;"
        "
        Vec3 closestPoint = origin + direction * t;"
        float distSq = Vec3DistanceSquared(closestPoint, transform->position);"
        "
        // Assume sphere collision for simplicity"
        float radius = 1.0f;"  // Would get from collider"
        if (distSq < radius * radius && t < closestDist) {"
            closestDist = t;"
            result.hitEntity = entity;"
            result.hitPoint = origin + direction * t;"
            result.isHit = true;"
        }"
    }"
    "
    return result;"
}"
"
std::vector<Entity> CombatSystem::meleeHits(const Vec3& center, float radius,"
                                   EntityManager& entities,"
                                   Entity ignoreEntity) {"
    std::vector<Entity> hits;"
    "
    auto allTransforms = entities.componentStorage.getAllComponents<TransformComponent>();"
    "
    for (const auto& pair : allTransforms) {"
        Entity entity = pair.first;"
        if (entity.id == ignoreEntity.id) continue;"
        "
        float dist = Vec3Distance(center, pair.second->position);"
        "
        if (dist <= radius) {"
            hits.push_back(entity);"
        }"
    }"
    "
    return hits;"
}"
"
void CombatSystem::onEntityKilled(const DamageInfo& damage, EntityManager& entities) {"
    std::cout << "[Combat] Entity " << damage.victim.id << " was killed!" << std::endl;"
    "
    // Award XP to killer"
    if (damage.attacker.id != 0) {"
        auto attackerData = entities.componentStorage.getComponent<PlayerDataComponent>(damage.attacker);"
        if (attackerData) {"
            attackerData->level.addXP(50.0f);"  // Would vary by enemy"
            attackerData->totalKills++;"
            "
            entities.componentStorage.addComponent<PlayerDataComponent>(damage.attacker, attackerData);"
        }"
    }"
    "
    // Drop loot (would implement loot table)"
    // Despawn entity after delay"
}"
"
void CombatSystem::registerDamageCallback(std::function<void(const DamageInfo&)> callback) {"
    damageCallbacks.push_back(callback);"
}"
"
int CombatSystem::getPriority() const {"
    return 50;"  // After physics, before AI"
}"
"
} // namespace Doomnite"
