// CombatSystem.hpp - C++ Combat System for Doomnite"
// FULL Production: Damage calculation, hit detection, combat effects"

#pragma once"

#include <string>"
#include <vector>"
#include <memory>"
#include <unordered_map>"
#include "ECS.hpp>"
#include "MathTypes.h>"

namespace Doomnite {"

// MARK: - Damage Type"

enum class DamageType {"
    Physical,"
    Fire,"
    Ice,"
    Lightning,"
    Poison,"
    Arcane,"
    Pure"  // Ignores armor"
};"

// MARK: - Damage Info"

struct DamageInfo {"
    float amount;"
    DamageType type;"
    Entity attacker;"
    Entity victim;"
    Vec3 hitPoint;"
    Vec3 hitNormal;"
    float penetration;"  // 0.0 = no penetration, 1.0 = full"
    bool isCritical;"
    "
    DamageInfo(float dmg = 0.0f, DamageType dmgType = DamageType::Physical)"
        : amount(dmg), type(dmgType), penetration(0.0f), isCritical(false) {}"
};"

// MARK: - Combat Component (ECS)"

struct CombatComponent : public Component {"
    float baseDamage;"
    float damageBonus;"  // From stats/equipment"
    float attackSpeed;"  // Attacks per second"
    float attackRange;"  // For melee"
    float criticalChance;"  // 0.0 to 1.0"
    float criticalMultiplier;"  // 1.5x, 2.0x, etc."
    std::unordered_map<DamageType, float> damageResitances;"  // Percentage"
    float armorPenetration;"  // 0.0 to 1.0"
    float lifesteal;"  // Percentage of damage healed"
    "
    CombatComponent(float baseDmg = 10.0f)"
        : baseDamage(baseDmg), damageBonus(0.0f), attackSpeed(1.0f),"
          attackRange(2.0f), criticalChance(0.05f), criticalMultiplier(1.5f),"
          armorPenetration(0.0f), lifesteal(0.0f) {"
        // Default resistances"
        damageResitances[DamageType::Physical] = 0.0f;"
        damageResitances[DamageType::Fire] = 0.0f;"
        damageResitances[DamageType::Ice] = 0.0f;"
        damageResitances[DamageType::Lightning] = 0.0f;"
    }"
    "
    float getTotalDamage() const {"
        return baseDamage + damageBonus;"
    }"
    "
    bool rollCritical() const {"
        // Simplified: random check"
        return ((rand() % 100) / 100.0f) < criticalChance;"
    }"
    "
    float applyDamageResistance(float damage, DamageType type) const {"
        auto it = damageResitances.find(type);"
        if (it != damageResitances.end()) {"
            float resistance = it->second;"
            damage *= (1.0f - resistance);"
        }"
        return damage;"
    }"
};"

// MARK: - Health Component (already in ECS.hpp, but adding combat methods)"

struct HealthComponent;  // Forward declaration"

// MARK: - Hit Result"

struct HitResult {"
    Entity hitEntity;"
    Vec3 hitPoint;"
    Vec3 hitNormal;"
    bool isHit;"
    "
    HitResult() : isHit(false) {}"
};"

// MARK: - Combat System (ECS System)"

class CombatSystem : public System {"
private:"
    std::vector<DamageInfo> pendingDamage;"
    std::vector<std::function<void(const DamageInfo&)>>> damageCallbacks;"
    "
public:"
    void update(EntityManager& entities, float deltaTime) override {"
        // Process pending damage"
        for (const auto& damage : pendingDamage) {"
            applyDamage(damage, entities);"
        }"
        pendingDamage.clear();"
        "
        // Update attack cooldowns"
        auto combatComps = entities.componentStorage.getAllComponents<CombatComponent>();"
        "
        for (auto& pair : combatComps) {"
            Entity entity = pair.first;"
            auto combat = pair.second;"
            "
            // Would update attack timers, etc."
        }"
    }"
    "
    // Deal damage (call this from other systems)"
    void dealDamage(const DamageInfo& damage, EntityManager& entities) {"
        pendingDamage.push_back(damage);"
    }"
    "
    // Apply damage to entity"
    void applyDamage(const DamageInfo& damage, EntityManager& entities) {"
        auto health = entities.componentStorage.getComponent<HealthComponent>(damage.victim);"
        auto combat = entities.componentStorage.getComponent<CombatComponent>(damage.victim);"
        "
        if (!health || !health->isAlive) return;"
        "
        // Calculate actual damage"
        float actualDamage = damage.amount;"
        "
        // Apply damage type resistance"
        if (combat) {"
            actualDamage = combat->applyDamageResistance(actualDamage, damage.type);"
        }"
        "
        // Apply armor penetration"
        if (damage.penetration > 0.0f && combat) {"
            // Would reduce effective armor"
        }"
        "
        // Critical hit"
        if (damage.isCritical) {"
            actualDamage *= 1.5f;"  // Simplified critical multiplier"
        }"
        "
        // Apply damage"
        bool wasKilled = health->takeDamage(actualDamage);"
        "
        // Lifesteal"
        if (damage.attacker.id != 0 && combat) {"
            float lifestealAmount = actualDamage * combat->lifesteal;"
            if (lifestealAmount > 0.0f) {"
                auto attackerHealth = entities.componentStorage.getComponent<HealthComponent>(damage.attacker);"
                if (attackerHealth) {"
                    attackerHealth->heal(lifestealAmount);"
                }"
            }"
        }"
        "
        // Fire callbacks"
        for (const auto& callback : damageCallbacks) {"
            callback(damage);"
        }"
        "
        // Notify other systems (would use an event system)"
        if (wasKilled) {"
            onEntityKilled(damage, entities);"
        }"
        "
        // Update back in storage"
        entities.componentStorage.addComponent<HealthComponent>(damage.victim, health);"
        if (damage.attacker.id != 0) {"
            entities.componentStorage.addComponent<CombatComponent>(damage.attacker, combat);"
        }"
    }"
    "
    // Raycast hit detection (hitscan weapons)"
    HitResult raycastHit(const Vec3& origin, const Vec3& direction,"
                              float maxDistance, EntityManager& entities,"
                              Entity ignoreEntity = Entity()) {"
        HitResult result;"
        "
        auto allTransforms = entities.componentStorage.getAllComponents<TransformComponent>();"
        float closestDist = maxDistance;"
        "
        for (const auto& pair : allTransforms) {"
            Entity entity = pair.first;"
            if (entity.id == ignoreEntity.id) continue;"
            "
            auto transform = pair.second;"
            auto collider = entities.componentStorage.getComponent<ColliderComponent>(entity);"
            if (!collider) continue;"
            "
            // Simplified ray-sphere check"
            Vec3 toCenter = transform->position - origin;"
            float t = Vec3Dot(toCenter, direction);"
            "
            if (t < 0) continue;"
            "
            Vec3 closestPoint = origin + direction * t;"
            float distSq = Vec3DistanceSquared(closestPoint, transform->position);"
            "
            // Assume sphere collision for simplicity"
            float radius = 1.0f;"  // Would get from collider"
            if (distSq < radius * radius && t < closestDist) {"
                closestDist = t;"
                result.hitEntity = entity;"
                result.hitPoint = origin + direction * t;"
                result.isHit = true;"
            }"
        }"
        "
        return result;"
    }"
    "
    // Melee hit detection (sphere check)"
    std::vector<Entity> meleeHits(const Vec3& center, float radius,"
                                   EntityManager& entities,"
                                   Entity ignoreEntity = Entity()) {"
        std::vector<Entity> hits;"
        "
        auto allTransforms = entities.componentStorage.getAllComponents<TransformComponent>();"
        "
        for (const auto& pair : allTransforms) {"
            Entity entity = pair.first;"
            if (entity.id == ignoreEntity.id) continue;"
            "
            auto transform = pair.second;"
            float dist = Vec3Distance(center, transform->position);"
            "
            if (dist <= radius) {"
                hits.push_back(entity);"
            }"
        }"
        "
        return hits;"
    }"
    "
    // Register damage callback"
    void registerDamageCallback(std::function<void(const DamageInfo&)> callback) {"
        damageCallbacks.push_back(callback);"
    }"
    "
private:"
    void onEntityKilled(const DamageInfo& damage, EntityManager& entities) {"
        // Handle death"
        // Would trigger death animation, loot drop, etc."
        "
        // Award XP to killer"
        if (damage.attacker.id != 0) {"
            auto attackerData = entities.componentStorage.getComponent<PlayerDataComponent>(damage.attacker);"
            if (attackerData) {"
                attackerData->level.addXP(50.0f);"  // Would vary by enemy"
                attackerData->totalKills++;"
                "
                entities.componentStorage.addComponent<PlayerDataComponent>(damage.attacker, attackerData);"
            }"
        }"
    }"
    "
public:"
    int getPriority() const override { return 50; }"  // After physics, before AI"
};"

} // namespace Doomnite"
