// CompleteGameEngine.cpp - MASTER Implementation"
// Initializes and runs ALL C++ systems together"

#include "CompleteGameEngine.hpp>"
#include <iostream>"
#include <algorithm>"

namespace Doomnite {"

// MARK: - CompleteGameEngine Implementation"

CompleteGameEngine::CompleteGameEngine() "
    : currentPhase(GamePhase::MainMenu),"
      isPaused(false), timeScale(1.0f), fixedDeltaTime(0.016f), fixedTimer(0.0f) {"
    "
    std::cout << "[Doomnite] Initializing ALL systems..." << std::endl;"
    initializeAllSystems();"
    std::cout << "[Doomnite] Engine ready!" << std::endl;"
}"

CompleteGameEngine::~CompleteGameEngine() {"
    shutdownAllSystems();"
}"

void CompleteGameEngine::initializeAllSystems() {"
    // Set entity manager"
    systemManager.setEntityManager(&entityManager);"
    "
    // Priority 10: Input System"
    inputSystem = std::make_shared<InputSystem>();"
    systemManager.addSystem(inputSystem);"
    "
    // Priority 20: Movement System"
    movementSystem = std::make_shared<MovementSystem>();"
    systemManager.addSystem(movementSystem);"
    "
    // Priority 30: Physics System"
    physicsSystem = std::make_shared<PhysicsSystem>();"
    systemManager.addSystem(physicsSystem);"
    "
    // Priority 40: Combat System"
    combatSystem = std::make_shared<CombatSystem>();"
    systemManager.addSystem(combatSystem);"
    "
    // Priority 50: AI System"
    aiSystem = std::make_shared<AISystem>();"
    systemManager.addSystem(aiSystem);"
    "
    // Priority 60: Spell Casting System"
    spellSystem = std::make_shared<SpellCastingSystem>();"
    systemManager.addSystem(spellSystem);"
    "
    // Priority 70: Quest System"
    questSystem = std::make_shared<QuestSystem>();"
    systemManager.addSystem(questSystem);"
    "
    // Priority 80: Day/Night System"
    dayNightSystem = std::make_shared<DayNightSystem>();"
    systemManager.addSystem(dayNightSystem);"
    "
    // Priority 90: Weather System"
    weatherSystem = std::make_shared<WeatherSystem>();"
    systemManager.addSystem(weatherSystem);"
    "
    // Priority 100: Zone System"
    zoneSystem = std::make_shared<ZoneSystem>();"
    systemManager.addSystem(zoneSystem);"
    "
    // Priority 110: Audio System"
    audioSystem = std::make_shared<AudioSystem>();"
    systemManager.addSystem(audioSystem);"
    "
    // Priority 120: Network System"
    networkSystem = std::make_shared<NetworkSystem>();"
    systemManager.addSystem(networkSystem);"
    "
    // Priority 130: Inventory System"
    inventorySystem = std::make_shared<InventorySystem>();"
    systemManager.addSystem(inventorySystem);"
    "
    // Initialize rendering resources"
    modelManager = std::make_unique<ModelManager>();"
    textureManager = std::make_unique<TextureManager>();"
    particleManager = std::make_unique<ParticleSystemManager>();"
    "
    // Create game state manager"
    gameStateManager = std::make_shared<GameStateManager>();"
    "
    std::cout << "[Doomnite] ALL systems initialized successfully!" << std::endl;"
}"

void CompleteGameEngine::update(float deltaTime) {"
    if (isPaused || currentPhase != GamePhase::Playing) return;"
    "
    float scaledDelta = deltaTime * timeScale;"
    "
    // Fixed update (for physics)"
    fixedTimer += scaledDelta;"
    while (fixedTimer >= fixedDeltaTime) {"
        // Fixed update would go here"
        // physicsSystem->fixedUpdate(fixedDeltaTime);"
        fixedTimer -= fixedDeltaTime;"
    }"
    "
    // Normal update - ALL systems"
    systemManager.updateAll(scaledDelta);"
    "
    // Update game state manager"
    if (gameStateManager) {"
        gameStateManager->update(scaledDelta);"
    }"
    "
    // Update rendering resources (not a system, but needs update)"
    // Would update GPU buffers, etc."
}"

// MARK: - Game Control"

void CompleteGameEngine::startNewGame() {"
    currentPhase = GamePhase::Playing;"
    isPaused = false;"
    "
    std::cout << "[Doomnite] Starting new game..." << std::endl;"
    "
    // Create player entity"
    Entity player = createPlayer(Vec3(0, 1, 0));"
    "
    // Set as current player in game state"
    if (gameStateManager) {"
        gameStateManager->setCurrentPlayer(player);"
    }"
    "
    // Start day/night cycle"
    if (dayNightSystem) {"
        // Would initialize day/night"
    }"
    "
    // Load starting zone"
    if (zoneSystem) {"
        auto* startingZone = zoneSystem->getZone("zone_starting");"
        if (startingZone) {"
            std::cout << "[Doomnite] Loaded zone: " << startingZone->name << std::endl;"
        }"
    }"
    "
    std::cout << "[Doomnite] New game started with player ID: " << player.id << std::endl;"
}"

void CompleteGameEngine::loadGame() {"
    currentPhase = GamePhase::Playing;"
    isPaused = false;"
    "
    // Load from local file or server"
    // Would deserialize game state"
    "
    std::cout << "[Doomnite] Game loaded!" << std::endl;"
}"

void CompleteGameEngine::saveGame() {"
    // Save to local file or server"
    // Would serialize game state"
    "
    if (gameStateManager) {"
        gameStateManager->save();"
    }"
    "
    std::cout << "[Doomnite] Game saved!" << std::endl;"
}"

void CompleteGameEngine::pause() {"
    isPaused = true;"
    "
    if (physicsSystem) {"
        physicsSystem->pausePhysics();"
    }"
    "
    std::cout << "[Doomnite] Game paused." << std::endl;"
}"

void CompleteGameEngine::resume() {"
    isPaused = false;"
    "
    if (physicsSystem) {"
        physicsSystem->resumePhysics();"
    }"
    "
    std::cout << "[Doomnite] Game resumed." << std::endl;"
}"

// MARK: - Entity Creation"

Entity CompleteGameEngine::createPlayer(const Vec3& position) {"
    Entity player = entityManager.createEntity();"
    "
    // Add Transform"
    auto transform = std::make_shared<TransformComponent>(position);"
    entityManager.getComponentStorage().addComponent<TransformComponent>(player, transform);"
    "
    // Add Velocity"
    auto velocity = std::make_shared<VelocityComponent>();"
    entityManager.getComponentStorage().addComponent<VelocityComponent>(player, velocity);"
    "
    // Add Health"
    auto health = std::make_shared<HealthComponent>(100.0f);"
    entityManager.getComponentStorage().addComponent<HealthComponent>(player, health);"
    "
    // Add Player Data"
    auto playerData = std::make_shared<PlayerDataComponent>();"
    entityManager.getComponentStorage().addComponent<PlayerDataComponent>(player, playerData);"
    "
    // Add Input (for player control)"
    auto input = std::make_shared<InputComponent>();"
    entityManager.getComponentStorage().addComponent<InputComponent>(player, input);"
    "
    return player;"
}"

Entity CompleteGameEngine::createEnemy(const Vec3& position, float health) {"
    Entity enemy = entityManager.createEntity();"
    "
    // Add Transform"
    auto transform = std::make_shared<TransformComponent>(position);"
    entityManager.getComponentStorage().addComponent<TransformComponent>(enemy, transform);"
    "
    // Add Velocity"
    auto velocity = std::make_shared<VelocityComponent>();"
    entityManager.getComponentStorage().addComponent<VelocityComponent>(enemy, velocity);"
    "
    // Add Health"
    auto healthComp = std::make_shared<HealthComponent>(health);"
    entityManager.getComponentStorage().addComponent<HealthComponent>(enemy, healthComp);"
    "
    // Add AI"
    auto ai = std::make_shared<EnemyAIComponent>();"
    entityManager.getComponentStorage().addComponent<EnemyAIComponent>(enemy, ai);"
    "
    return enemy;"
}"

Entity CompleteGameEngine::createCompanion(const Vec3& position, const std::string& type) {"
    Entity companion = entityManager.createEntity();"
    "
    // Add Transform"
    auto transform = std::make_shared<TransformComponent>(position);"
    entityManager.getComponentStorage().addComponent<TransformComponent>(companion, transform);"
    "
    // Add Companion Component"
    auto companionComp = std::make_shared<CompanionComponent>();"
    entityManager.getComponentStorage().addComponent<CompanionComponent>(companion, companionComp);"
    "
    return companion;"
}"

// MARK: - Getters"

float CompleteGameEngine::getPlayerHealth(Entity player) {"
    auto health = entityManager.getComponentStorage().getComponent<HealthComponent>(player);"
    if (health) {"
        return health->currentHealth;"
    }"
    return 0.0f;"
}"
float CompleteGameEngine::getPlayerMaxHealth(Entity player) {"
    auto health = entityManager.getComponentStorage().getComponent<HealthComponent>(player);"
    if (health) {"
        return health->maxHealth;"
    }"
    return 0.0f;"
}"
bool CompleteGameEngine::isPlayerAlive(Entity player) {"
    auto health = entityManager.getComponentStorage().getComponent<HealthComponent>(player);"
    if (health) {"
        return health->isAlive;"
    }"
    return false;"
}"

// MARK: - Shutdown"

void CompleteGameEngine::shutdownAllSystems() {"
    systemManager.~SystemManager();"
    entityManager.~EntityManager();"
    "
    modelManager.reset();"
    textureManager.reset();"
    particleManager.reset();"
    "
    inputSystem.reset();"
    movementSystem.reset();"
    physicsSystem.reset();"
    combatSystem.reset();"
    aiSystem.reset();"
    spellSystem.reset();"
    questSystem.reset();"
    dayNightSystem.reset();"
    weatherSystem.reset();"
    zoneSystem.reset();"
    audioSystem.reset();"
    networkSystem.reset();"
    inventorySystem.reset();"
    gameStateManager.reset();"
    "
    std::cout << "[Doomnite] ALL systems shut down!" << std::endl;"
}"

} // namespace Doomnite"
