// DoomniteEngine-Bridge.mm - ACTUAL WORKING BRIDGE"
// Connects C++ CompleteGameEngine to iOS/Swift"

#import <Foundation/Foundation.h>"
#import <Metal/Metal.h>"
#import <simd/simd.h>"

#include "CompleteGameEngine.hpp>"

using namespace Doomnite;"

// MARK: - C++ Engine Creation"

extern "C" {"
    void* CreateGameEngine() {"
        auto engine = new CompleteGameEngine();"
        return static_cast<void*>(engine);"
    }"
    "
    void DestroyGameEngine(void* enginePtr) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        delete engine;"
    }"
    "
    void UpdateGameEngine(void* enginePtr, float deltaTime) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (engine) engine->update(deltaTime);"
    }"
    "
    void PauseGameEngine(void* enginePtr) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (engine) engine->pause();"
    }"
    "
    void ResumeGameEngine(void* enginePtr) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (engine) engine->resume();"
    }"
    "
    // Entity creation"
    uint32_t CreatePlayer(void* enginePtr, float x, float y, float z) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (!engine) return 0;"
        Entity player = engine->createPlayer(Vec3Make(x, y, z));"
        return player.id;"
    }"
    "
    uint32_t CreateEnemy(void* enginePtr, float x, float y, float z, float health) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (!engine) return 0;"
        Entity enemy = engine->createEnemy(Vec3Make(x, y, z), health);"
        return enemy.id;"
    }"
    "
    // Component management"
    void AddTransform(void* enginePtr, uint32_t entityId, float x, float y, float z) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (!engine) return;"
        Entity entity(entityId, 0);"
        auto transform = std::make_shared<TransformComponent>(Vec3Make(x, y, z));"
        engine->getEntityManager().getComponentStorage().addComponent<TransformComponent>(entity, transform);"
    }"
    "
    void AddHealth(void* enginePtr, uint32_t entityId, float health) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (!engine) return;"
        Entity entity(entityId, 0);"
        auto healthComp = std::make_shared<HealthComponent>(health);"
        engine->getEntityManager().getComponentStorage().addComponent<HealthComponent>(entity, healthComp);"
    }"
    "
    // Game state"
    float GetPlayerHealth(void* enginePtr, uint32_t playerId) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (!engine) return 0.0f;"
        Entity player(playerId, 0);"
        return engine->getPlayerHealth(player);"
    }"
    "
    bool IsPlayerAlive(void* enginePtr, uint32_t playerId) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (!engine) return false;"
        Entity player(playerId, 0);"
        return engine->isPlayerAlive(player);"
    }"
    "
    // Game control"
    void StartNewGame(void* enginePtr) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (engine) engine->startNewGame();"
    }"
    "
    void LoadGame(void* enginePtr) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (engine) engine->loadGame();"
    }"
    "
    void SaveGame(void* enginePtr) {"
        auto* engine = static_cast<CompleteGameEngine*>(enginePtr);"
        if (engine) engine->saveGame();"
    }"
}"

// MARK: - ObjC++ Wrapper for Swift"

@interface DoomniteEngine : NSObject {"
    void* _enginePtr;"
    BOOL _isPaused;"
}"
"
@property (nonatomic, readonly) void* enginePtr;"
@property (nonatomic, readonly) BOOL isRunning;"
"
- (instancetype)init {"
    self = [super init];"
    if (self) {"
        _enginePtr = CreateGameEngine();"
        _isPaused = NO;"
    }"
    return self;"
}"
"
- (void)update:(float)deltaTime {"
    if (_enginePtr && !_isPaused) {"
        UpdateGameEngine(_enginePtr, deltaTime);"
    }"
}"
"
- (void)pause {"
    if (_enginePtr) {"
        PauseGameEngine(_enginePtr);"
        _isPaused = YES;"
    }"
}"
"
- (void)resume {"
    if (_enginePtr) {"
        ResumeGameEngine(_enginePtr);"
        _isPaused = NO;"
    }"
}"
"
- (uint32_t)createPlayerAt:(simd_float3)position {"
    if (!_enginePtr) return 0;"
    return CreatePlayer(_enginePtr, position.x, position.y, position.z);"
}"
"
- (uint32_t)createEnemyAt:(simd_float3)position health:(float)health {"
    if (!_enginePtr) return 0;"
    return CreateEnemy(_enginePtr, position.x, position.y, position.z, health);"
}"
"
- (float)getPlayerHealth:(uint32_t)playerId {"
    if (!_enginePtr) return 0.0f;"
    return GetPlayerHealth(_enginePtr, playerId);"
}"
"
- (BOOL)isPlayerAlive:(uint32_t)playerId {"
    if (!_enginePtr) return NO;"
    return IsPlayerAlive(_enginePtr, playerId) ? YES : NO;"
}"
"
- (void)startNewGame {"
    if (_enginePtr) StartNewGame(_enginePtr);"
}"
"
- (void)loadGame {"
    if (_enginePtr) LoadGame(_enginePtr);"
}"
"
- (void)saveGame {"
    if (_enginePtr) SaveGame(_enginePtr);"
}"
"
- (void)dealloc {"
    if (_enginePtr) {"
        DestroyGameEngine(_enginePtr);"
        _enginePtr = nullptr;"
    }"
    [super dealloc];"
}"
"
@end"
