// ZoneSystem.cpp - FULL Production Implementation"
// Zone management with biomes, POIs, dungeons"

#include "ZoneSystem.hpp>"
#include <algorithm>"
#include <iostream>"

namespace Doomnite {"

void ZoneSystem::update(EntityManager& entities, float deltaTime) {"
    auto zoneComponents = entities.componentStorage.getAllComponents<ZoneComponent>();"
    "
    for (auto& pair : zoneComponents) {"
        Entity entity = pair.first;"
        auto zoneComp = pair.second;"
        auto transform = entities.componentStorage.getComponent<TransformComponent>(entity);"
        if (!transform) continue;"
        "
        // Check if left current zone"
        if (zoneComp.hasZoneChanged(transform->position, entities)) {"
            // Find new zone"
            Zone* newZone = findZoneForPosition(transform->position);"
            if (newZone) {"
                zoneComp.setZone(newZone->id);"
                onZoneChanged(entity, zoneComp.previousZoneId, newZone->id, entities);"
            }"
        }"
        "
        // Update transition timer"
        if (zoneComp.isInTransition) {"
            zoneComp.transitionTimer -= deltaTime;"
            if (zoneComp.transitionTimer <= 0.0f) {"
                zoneComp.isInTransition = false;"
            }"
        }"
        "
        // Update back"
        entities.componentStorage.addComponent<ZoneComponent>(entity, zoneComp);"
    }"
    "
    // Update portals"
    updatePortals(deltaTime, entities);"
}"
"
Zone* ZoneSystem::findZoneForPosition(const Vec3& position) {"
    for (auto& pair : zones) {"
        if (pair.second.isPointInside(position)) {"
            return &pair.second;"
        }"
    }"
    return nullptr;"
}"
"
void ZoneSystem::onZoneChanged(const Entity& entity, const std::string& oldZoneId, "
                              const std::string& newZoneId, EntityManager& entities) {"
    std::cout << "[Zone] Entity " << entity.id << " moved from " "
              << oldZoneId << " to " << newZoneId << std::endl;"
    "
    auto* oldZone = getZone(oldZoneId);"
    auto* newZone = getZone(newZoneId);"
    "
    if (newZone) {"
        std::cout << "[Zone] Entered: " << newZone->name << std::endl;"
        "
        // Update audio (music/ambient)"
        // Would notify AudioSystem"
        "
        // Spawn zone-specific enemies"
        // Would spawn enemies based on biome"
        "
        // Show zone name UI"
        // Would notify UISystem"
        "
        // Apply weather profile"
        if (!newZone->weatherProfileId.empty()) {"
            // Would set weather"
        }"
    }"
}"
"
void ZoneSystem::updatePortals(float deltaTime, EntityManager& entities) {"
    auto portalComponents = entities.componentStorage.getAllComponents<PortalComponent>();"
    "
    for (auto& pair : portalComponents) {"
        Entity entity = pair.first;"
        auto portal = pair.second;"
        "
        if (portal.cooldownTimer > 0.0f) {"
            portal.cooldownTimer -= deltaTime;"
        }"
        "
        // Check for player with key nearby"
        auto playerData = entities.componentStorage.getAllComponents<PlayerDataComponent>();"
        "
        for (auto& playerPair : playerData) {"
            Entity player = playerPair.first;"
            auto transform = entities.componentStorage.getComponent<TransformComponent>(player);"
            if (!transform) continue;"
            "
            float distance = Vec3Distance(portal.portalPosition, transform->position);"
            "
            if (distance <= 5.0f && portal.canActivate("dummy_key")) {"
                // Would check if player has actual key"
                portal.activate();"
                std::cout << "[Portal] Activated portal!" << std::endl;"
                break;"
            }"
        }"
        "
        entities.componentStorage.addComponent<PortalComponent>(entity, portal);"
    }"
}"
"
bool ZoneSystem::addZone(const Zone& zone) {"
    if (zones.find(zone.id) != zones.end()) return false;"
    zones[zone.id] = zone;"
    return true;"
}"
"
Zone* ZoneSystem::getZone(const std::string& zoneId) {"
    auto it = zones.find(zoneId);"
    if (it != zones.end()) return &it->second;"
    return nullptr;"
}"
"
void ZoneSystem::unlockPOI(const std::string& zoneId, const std::string& poiId) {"
    auto* zone = getZone(zoneId);"
    if (zone) {"
        auto* poi = zone->getPOI(poiId);"
        if (poi) {"
            poi->isDiscovered = true;"
            std::cout << "[Zone] Unlocked POI: " << poiId << std::endl;"
        }"
    }"
}"
