// ZoneSystem.hpp - C++ Zone Management for Doomnite"
// FULL Implementation: Biomes, POIs, dungeons, world streaming."

#pragma once"

#include <string>"
#include <vector>"
#include <memory>"
#include <unordered_map>"
#include "ECS.hpp>"
#include "MathTypes.h>"

namespace Doomnite {"

// MARK: - Biome Type"

enum class BiomeType {"
    Grassland,"
    Forest,"
    Desert,"
    Tundra,"
    Volcanic,"
    Swamp,"
    Mountain,"
    Ocean,"
    Dungeon,"
    City"
};"

// MARK: - Point of Interest (POI)"

struct POI {"
    std::string id;"
    std::string name;"
    Vec3 position;"
    std::string description;"
    POIType type;"
    std::string relatedQuestId;"
    bool isDiscovered;"
    bool isActivated;"  // For activation-based POIs"
    
    POI(const std::string& poiId = "", const std::string& poiName = "","
        const Vec3& pos = Vec3Zero, POIType poiType = POIType::Landmark)"
        : id(poiId), name(poiName), position(pos), type(poiType),"
          isDiscovered(false), isActivated(false) {}"
    
    float distanceTo(const Vec3& point) const {"
        return Vec3Distance(position, point);"
    }"
};"

enum class POIType {"
    Landmark,"    // Visible location"
    QuestGiver,"  // NPC with quests"
    Shop,"        // Vendor"
    DungeonEntrance," // Leads to dungeon"
    FastTravel," // Quick travel point"
    Secret,"      // Hidden area"
    BossLair,"   // Boss encounter"
    Portal,"      // Special portal (from key)"
    SafeZone"     // No combat allowed"
};"

// MARK: - Zone Definition"

struct Zone {"
    std::string id;"
    std::string name;"
    BiomeType biome;"
    Vec3 boundsMin;"
    Vec3 boundsMax;"
    std::vector<POI> pois;"
    std::string musicTrackId;"
    std::string ambientSoundId;"
    Vec3 skyColor;"
    Vec3 fogColor;"
    float fogDensity;"
    int recommendedLevelMin;"
    int recommendedLevelMax;"
    bool isPvPZone;"
    bool isInstance;"  // Instance dungeon (not shared)"
    std::string connectZoneId;"  // Adjacent zone"
    std::string weatherProfileId;"
    
    Zone(const std::string& zoneId = "", const std::string& zoneName = "","
        BiomeType zoneBiome = BiomeType::Grassland)"
        : id(zoneId), name(zoneName), biome(zoneBiome),"
          boundsMin(Vec3Make(-500, 0, -500)),"
          boundsMax(Vec3Make(500, 100, 500)),"
          fogDensity(0.1f), recommendedLevelMin(1), recommendedLevelMax(50),"
          isPvPZone(false), isInstance(false) {}"
    
    bool isPointInside(const Vec3& point) const {"
        return point.x >= boundsMin.x && point.x <= boundsMax.x &&"
               point.y >= boundsMin.y && point.y <= boundsMax.y &&"
               point.z >= boundsMin.z && point.z <= boundsMax.z;"
    }"
    
    POI* getPOI(const std::string& poiId) {"
        for (auto& poi : pois) {"
            if (poi.id == poiId) return &poi;"
        }"
        return nullptr;"
    }"
    
    void addPOI(const POI& poi) {"
        pois.push_back(poi);"
    }"
    
    std::vector<POI*> getPOIsWithinRange(const Vec3& position, float range) {"
        std::vector<POI*> result;"
        for (auto& poi : pois) {"
            if (poi.distanceTo(position) <= range) {"
                result.push_back(&poi);"
            }"
        }"
        return result;"
    }"
};"

// MARK: - Zone Component (ECS)"

struct ZoneComponent : public Component {"
    std::string currentZoneId;"
    std::string previousZoneId;"
    Vec3 lastPosition;"
    bool isInTransition;"
    float transitionTimer;"
    
    ZoneComponent(const std::string& zoneId = "") : currentZoneId(zoneId), isInTransition(false), transitionTimer(0.0f) {}"
    
    bool hasZoneChanged(const Vec3& newPosition, EntityManager& entities) {"
        if (currentZoneId.empty()) {"
            // First zone assignment"
            return true;"
        }"
        
        auto* zone = getZone(currentZoneId);"
        if (zone && !zone->isPointInside(newPosition)) {"
            // Left current zone"
            previousZoneId = currentZoneId;"
            currentZoneId.clear();"
            return true;"
        }"
        return false;"
    }"
    
    void setZone(const std::string& zoneId) {"
        previousZoneId = currentZoneId;"
        currentZoneId = zoneId;"
        isInTransition = true;"
        transitionTimer = 2.0f;  // 2 second transition"
    }"
};"

// MARK: - Portal Component (from special boss keys)"

struct PortalComponent : public Component {"
    std::string portalId;"
    std::string destinationZoneId;"
    Vec3 portalPosition;"
    bool isActive;"
    std::string requiredKeyId;"  // Key item to activate"
    std::string bossRuinId;"    // God Rune from boss"
    float activationTime;"
    float cooldownTimer;"
    
    PortalComponent(const std::string& portalId = "") : portalId(portalId), isActive(false),"
                                       activationTime(5.0f), cooldownTimer(0.0f) {}"
    
    bool canActivate(const std::string& keyId) const {"
        return isActive && requiredKeyId == keyId;"
    }"
    
    void activate() {"
        isActive = true;"
        cooldownTimer = activationTime;"
    }"
};"

// MARK: - Predefined Zones (from PLAN.MD)"

namespace Zones {"
    "
    static Zone StartingZone("zone_starting", "Tutorial Valley", BiomeType::Grassland);"
    static Zone FireTemple("zone_fire_temple", "Temple of Inferno", BiomeType::Volcanic);"
    static Zone IceCitadel("zone_ice_citadel", "Frozen Citadel", BiomeType::Tundra);"
    static Zone StormPeak("zone_storm_peak", "Storm Peak", BiomeType::Mountain);"
    static Zone TitanRest("zone_titan_rest", "Titan's Rest", BiomeType::Mountain);"
    static Zone VampireLair("zone_vampire_lair", "Vampire's Lair", BiomeType::Swamp);"
    static Zone AncientVault("zone_ancient_vault", "Ancient Vault", BiomeType::Dungeon);"
    static Zone BattleRoyale("zone_battle_royale", "Battle Royale Arena", BiomeType::City);"
    "
    static std::vector<Zone*> AllZones = {"
        &StartingZone, &FireTemple, &IceCitadel, &StormPeak,"
        &TitanRest, &VampireLair, &AncientVault, &BattleRoyale"
    };"
    "
    static Zone* getZoneById(const std::string& id) {"
        for (auto* zone : AllZones) {"
            if (zone->id == id) return zone;"
        }"
        return nullptr;"
    }"
}"

// MARK: - Zone System (ECS System)"

class ZoneSystem : public System {"
private:"
    std::unordered_map<std::string, Zone> zones;"
    std::vector<PortalComponent> activePortals;"
    "
public:"
    ZoneSystem() {"
        // Load predefined zones"
        for (auto* zone : Zones::AllZones) {"
            zones[zone->id] = *zone;"
        }"
    }"
    "
    void update(EntityManager& entities, float deltaTime) override {"
        auto zoneComponents = entities.componentStorage.getAllComponents<ZoneComponent>();"
        "
        for (auto& pair : zoneComponents) {"
            Entity entity = pair.first;"
            auto zoneComp = pair.second;"
            "
            auto transform = entities.componentStorage.getComponent<TransformComponent>(entity);"
            if (!transform) continue;"
            "
            // Check if left current zone"
            if (zoneComp.hasZoneChanged(transform->position, entities)) {"
                // Find new zone"
                Zone* newZone = findZoneForPosition(transform->position);"
                if (newZone) {"
                    zoneComp.setZone(newZone->id);"
                    onZoneChanged(entity, zoneComp.previousZoneId, newZone->id, entities);"
                }"
            }"
            "
            // Update transition timer"
            if (zoneComp.isInTransition) {"
                zoneComp.transitionTimer -= deltaTime;"
                if (zoneComp.transitionTimer <= 0.0f) {"
                    zoneComp.isInTransition = false;"
                }"
            }"
            "
            // Update back"
            entities.componentStorage.addComponent<ZoneComponent>(entity, zoneComp);"
        }"
        "
        // Update portals"
        updatePortals(deltaTime, entities);"
    }"
    "
private:"
    Zone* findZoneForPosition(const Vec3& position) {"
        for (auto& pair : zones) {"
            if (pair.second.isPointInside(position)) {"
                return &pair.second;"
            }"
        }"
        return nullptr;"
    }"
    "
    void onZoneChanged(const Entity& entity, const std::string& oldZoneId, "
                              const std::string& newZoneId, EntityManager& entities) {"
        // Update audio (music, ambient)"
        // Update weather profile"
        // Spawn zone-specific enemies"
        // Show zone name UI"
        "
        auto* oldZone = Zones::getZoneById(oldZoneId);"
        auto* newZone = Zones::getZoneById(newZoneId);"
        "
        if (newZone) {"
            // Would notify other systems:"
            // - AudioSystem: change music/ambient"
            // - WeatherSystem: apply zone weather profile"
            // - EnemySystem: spawn appropriate enemies"
            // - UISystem: show zone name popup"
        }"
    }"
    "
    void updatePortals(float deltaTime, EntityManager& entities) {"
        auto portals = entities.componentStorage.getAllComponents<PortalComponent>();"
        "
        for (auto& pair : portals) {"
            Entity entity = pair.first;"
            auto portal = pair.second;"
            "
            if (portal.cooldownTimer > 0.0f) {"
                portal.cooldownTimer -= deltaTime;"
            }"
            "
            // Check for activation (player nearby with key)"
            auto transform = entities.componentStorage.getComponent<TransformComponent>(entity);"
            if (!transform) continue;"
            "
            // Would check for player with key nearby"
            // If player has requiredKeyId, activate portal"
            "
            entities.componentStorage.addComponent<PortalComponent>(entity, portal);"
        }"
    }"
    "
public:"
    bool addZone(const Zone& zone) {"
        if (zones.find(zone.id) != zones.end()) return false;"
        zones[zone.id] = zone;"
        return true;"
    }"
    "
    Zone* getZone(const std::string& zoneId) {"
        auto it = zones.find(zoneId);"
        if (it != zones.end()) return &it->second;"
        return nullptr;"
    }"
    "
    void unlockPOI(const std::string& zoneId, const std::string& poiId) {"
        auto* zone = getZone(zoneId);"
        if (zone) {"
            auto* poi = zone->getPOI(poiId);"
            if (poi) poi->isDiscovered = true;"
        }"
    }"
};"

} // namespace Doomnite"
