// GameHUDView.swift"
// Doomnite - Full In-Game HUD with all gameplay indicators."

import SwiftUI"
import GameKit"

struct GameHUDView: View {"
    @ObservedObject var gameEngine: GameEngine"
    @State private var showPauseMenu = false"
    @State private var showMap = false"
    @State private var showQuests = false"
    @State private var showInventory = false"
    @State private var showSpellBook = false"
    "
    var body: some View {"
        GeometryReader { geometry in"
            ZStack {"
                // Main game view (Metal rendered)"
                GameViewContainer(engine: gameEngine)"
                    .edgesIgnoringSafeArea()"
                "
                // HUD Overlay"
                VStack(spacing: 0) {"
                    // Top bar: Stats, minimap, objectives"
                    TopBarView(gameEngine: gameEngine)"
                        .padding(.horizontal)"
                        .padding(.top, geometry.safeAreaInsets.top)"
                    "
                    Spacer()"
                    "
                    // Bottom bar: Weapons, spells, controls)"
                    BottomBarView(gameEngine: gameEngine)"
                        .padding(.horizontal)"
                        .padding(.bottom, geometry.safeAreaInsets.bottom)"
                }"
                .allowsHitTesting(false) // Let touches pass through to game"
                "
                // Pause button"
                VStack {"
                    HStack {"
                        Spacer()"
                        Button(action: { showPauseMenu = true }) {"
                            Image(systemName: "pause.circle.fill")"
                                .resizable()"
                                .frame(width: 30, height: 30)"
                                .foregroundColor(.white)"
                        }"
                        .padding()"
                    }"
                    Spacer()"
                }"
                "
                // Quick slots (left side)"
                VStack(spacing: 10) {"
                    ForEach(0..<4) { index in"
                        QuickSlotView(slotIndex: index, gameEngine: gameEngine)"
                    }"
                }"
                .padding(.leading)"
                .padding(.top, 100)"
                "
                // Damage numbers, floating text"
                FloatingTextContainer()"
                "
                // Modals"
                .sheet(isPresented: $showPauseMenu) {"
                    PauseMenuView(gameEngine: gameEngine, isPresented: $showPauseMenu)"
                }"
                .sheet(isPresented: $showMap) {"
                    MapView(gameEngine: gameEngine)"
                }"
                .sheet(isPresented: $showQuests) {"
                    QuestTrackerView(gameEngine: gameEngine)"
                }"
                .sheet(isPresented: $showInventory) {"
                    InventoryView(gameEngine: gameEngine)"
                }"
                .sheet(isPresented: $showSpellBook) {"
                    SpellBookView(gameEngine: gameEngine)"
                }"
            }"
        }"
    }"
}"

// MARK: - Top Bar"

struct TopBarView: View {"
    @ObservedObject var gameEngine: GameEngine"
    "
    var body: some View {"
        HStack(spacing: 15) {"
            // Player portrait & health"
            HStack(spacing: 8) {"
                PlayerPortraitView()"
                "
                VStack(alignment: .leading, spacing: 4) {"
                    // Health bar"
                    HealthBarView(value: gameEngine.playerHealth, maxValue: gameEngine.playerMaxHealth)"
                        .frame(width: 120, height: 12)"
                    "
                    // Mana bar"
                    HealthBarView(value: gameEngine.playerMana, maxValue: gameEngine.playerMaxMana, color: .blue)"
                        .frame(width: 120, height: 8)"
                    "
                    // Level & XP"
                    Text("Lv \(gameEngine.playerLevel) - \(Int(gameEngine.playerXP))%")"
                        .font(.system(size: 10))"
                        .foregroundColor(.gray)"
                }"
            }"
            "
            Spacer()"
            "
            // Current quest objective"
            if let objective = gameEngine.currentObjective {"
                VStack(spacing: 4) {"
                    Text(objective.title)"
                        .font(.caption.bold())"
                        .foregroundColor(.yellow)"
                    "
                    Text(objective.description)"
                        .font(.system(size: 10))"
                        .foregroundColor(.gray)"
                        .lineLimit(2)"
                }"
                .padding(8)"
                .background(Color.black.opacity(0.7))"
                .cornerRadius(8)"
            }"
            "
            Spacer()"
            "
            // Minimap toggle"
            Button(action: { showMap.toggle() }) {"
                Image(systemName: "map")"
                    .foregroundColor(.white)"
            }"
            "
            // Quest log toggle"
            Button(action: { showQuests.toggle() }) {"
                Image(systemName: "list.bullet")"
                    .foregroundColor(.white)"
            }"
        }"
    }"
}"

// MARK: - Bottom Bar"

struct BottomBarView: View {"
    @ObservedObject var gameEngine: GameEngine"
    @State private var selectedWeaponIndex = 0"
    "
    var body: some View {"
        HStack(spacing: 15) {"
            // Movement joystick (simplified - would use custom control)"
            JoystickView()"
                .frame(width: 100, height: 100)"
            "
            Spacer()"
            "
            // Weapon slots"
            HStack(spacing: 8) {"
                ForEach(0..<3) { index in"
                    WeaponSlotView(slotIndex: index, gameEngine: gameEngine)"
                }"
                "
                // Spell book button"
                Button(action: { showSpellBook = true }) {"
                    Image(systemName: "book.fill")"
                        .foregroundColor(.purple)"
                        .frame(width: 40, height: 40)"
                }"
            }"
            "
            Spacer()"
            "
            // Action buttons"
            HStack(spacing: 10) {"
                // Jump"
                ActionButton(systemName: "arrow.up", action: { gameEngine.jumpPlayer() })"
                "
                // Attack"
                ActionButton(systemName: "bolt.fill", action: { gameEngine.attack() })"
                "
                // Special ability"
                ActionButton(systemName: "star.fill", action: { gameEngine.useSpecialAbility() }) {"
                    .foregroundColor(.yellow)"
                }"
                "
                // Inventory"
                ActionButton(systemName: "bag.fill", action: { showInventory = true })"
            }"
        }"
    }"
}"

// MARK: - Subviews"

struct PlayerPortraitView: View {"
    var body: some View {"
        Circle()"
            .fill(Color.gray)"
            .frame(width: 40, height: 40)"
            .overlay(Text("P").foregroundColor(.white))"
    }"
}"

struct HealthBarView: View {"
    let value: Float"
    let maxValue: Float"
    var color: Color = .green"
    "
    var body: some View {"
        GeometryReader { geo in"
            ZStack(alignment: .leading) {"
                // Background"
                Rectangle()"
                    .fill(Color.gray.opacity(0.3))"
                    .frame(width: geo.size.width, height: geo.size.height)"
                "
                // Fill"
                Rectangle()"
                    .fill(color)"
                    .frame(width: geo.size.width * CGFloat(min(value / maxValue, 1.0)), height: geo.size.height)"
                    .animation(.linear(duration: 0.1))"
            }"
            .cornerRadius(4)"
        }"
    }"
}"

struct QuickSlotView: View {"
    let slotIndex: Int"
    @ObservedObject var gameEngine: GameEngine"
    "
    var body: some View {"
        VStack {"
            ZStack {"
                Rectangle()"
                    .fill(Color.gray.opacity(0.5))"
                    .frame(width: 50, height: 50)"
                    .cornerRadius(8)"
                "
                // Item icon (would load from inventory)"
                Image(systemName: "star.fill")"
                    .foregroundColor(.yellow)"
                    .font(.system(size: 20))"
            }"
            Text("\(slotIndex + 1)")"
                .font(.system(size: 8))"
                .foregroundColor(.gray)"
        }"
    }"
}"

struct WeaponSlotView: View {"
    let slotIndex: Int"
    @ObservedObject var gameEngine: GameEngine"
    "
    var body: some View {"
        VStack {"
            ZStack {"
                Rectangle()"
                    .fill(Color.gray.opacity(0.5))"
                    .frame(width: 60, height: 60)"
                    .cornerRadius(8)"
                    .border(gameEngine.selectedWeaponIndex == slotIndex ? Color.yellow : Color.clear, width: 2)"
                "
                // Weapon icon"
                Image(systemName: "bolt.shield.fill")"  // Placeholder"
                    .foregroundColor(.orange)"
                    .font(.system(size: 24))"
            }"
            "
            // Ammo count"
            Text("30/30")"
                .font(.system(size: 8))"
                .foregroundColor(.gray)"
        }"
        .onTapGesture {"
            gameEngine.selectWeapon(at: slotIndex)"
        }"
    }"
}"

struct ActionButton: View {"
    let systemName: String"
    let action: () -> Void"
    var color: Color = .white"
    "
    var body: some View {"
        Button(action: action) {"
            Image(systemName: systemName)"
                .font(.system(size: 24))"
                .foregroundColor(color)"
                .frame(width: 44, height: 44)"
                .background(Color.gray.opacity(0.3))"
                .cornerRadius(8)"
        }"
        .buttonStyle(PlainButtonStyle())"
    }"
}"

struct JoystickView: View {"
    @State private var dragOffset = CGSize.zero"
    @State private var isDragging = false"
    "
    var body: some View {"
        ZStack {"
            // Base"
            Circle()"
                .fill(Color.gray.opacity(0.3))"
                .frame(width: 100, height: 100)"
            "
            // Knob"
            Circle()"
                .fill(Color.white.opacity(0.7))"
                .frame(width: 40, height: 40)"
                .offset(x: dragOffset.width, y: dragOffset.height)"
        }"
        .gesture("
            DragGesture()"
                .onChanged { value in"
                    dragOffset = value.translation"
                    isDragging = true"
                    // Would update player movement direction"
                }"
                .onEnded { _ in"
                    withAnimation(.spring()) {"
                        dragOffset = .zero"
                    }"
                    isDragging = false"
                }"
        )"
    }"
}"

struct FloatingTextContainer: View {"
    var body: some View {"
        // Would show floating damage numbers, "+XP", etc."
        // In real implementation: overlay on game view"
        EmptyView()"
    }"
}"

// MARK: - Pause Menu"

struct PauseMenuView: View {"
    @ObservedObject var gameEngine: GameEngine"
    @Binding var isPresented: Bool"
    "
    var body: some View {"
        ZStack {"
            Color.black.opacity(0.7)).edgesIgnoringSafeArea()"
            "
            VStack(spacing: 20) {"
                Text("PAUSED")"
                    .font(.largeTitle.bold())"
                    .foregroundColor(.white)"
                "
                MenuButton(title: "Resume", icon: "play.fill") {"
                    isPresented = false"
                }"
                "
                MenuButton(title: "Settings", icon: "gearshape.fill") {"
                    // Open settings"
                }"
                "
                MenuButton(title: "Quit to Menu", icon: "xmark.circle.fill") {"
                    gameEngine.quitToMenu()"
                }"
            }"
        }"
    }"
}"

// MARK: - Placeholder Views (would be full implementations)"

struct GameViewContainer: View {"
    let engine: GameEngine"
    "
    var body: some View {"
        Color.black.edgesIgnoringSafeArea()"
        // Metal view would be here"
    }"
}"

struct MapView: View {"
    @ObservedObject var gameEngine: GameEngine"
    "
    var body: some View {"
        NavigationView {"
            Text("World Map")"
                .font(.title)"
        }"
        .navigationBarTitle("Map")"
    }"
}"

struct QuestTrackerView: View {"
    @ObservedObject var gameEngine: GameEngine"
    "
    var body: some View {"
        NavigationView {"
            List(gameEngine.activeQuests) { quest in"
                QuestRowView(quest: quest)"
            }"
        }"
        .navigationBarTitle("Active Quests")"
    }"
}"

struct QuestRowView: View {"
    let quest: QuestInfo"
    "
    var body: some View {"
        HStack {"
            VStack(alignment: .leading) {"
                Text(quest.title).bold()"
                Text(quest.objectiveDescription)"
                    .font(.caption)"
                    .foregroundColor(.gray)"
            }"
            Spacer()"
            Text("\(Int(quest.progress * 100))%")"
                .foregroundColor(.yellow)"
        }"
    }"
}"

struct InventoryView: View {"
    @ObservedObject var gameEngine: GameEngine"
    "
    var body: some View {"
        NavigationView {"
            Text("Inventory")"
                .font(.title)"
        }"
        .navigationBarTitle("Inventory")"
    }"
}"

struct SpellBookView: View {"
    @ObservedObject var gameEngine: GameEngine"
    "
    var body: some View {"
        NavigationView {"
            Text("Spell Book")"
                .font(.title)"
        }"
        .navigationBarTitle("Spells")"
    }"
}"

struct JoystickView: View {"
    var body: some View {"
        Circle()"
            .fill(Color.gray.opacity(0.3))"
            .frame(width: 100, height: 100)"
    }"
}"

// MARK: - Preview"

struct GameHUDView_Previews: PreviewProvider {"
    static var previews: some View {"
        GameHUDView(gameEngine: GameEngine())"
    }"
}"
