// NetworkSystem.hpp - C++ Networking for Doomnite"
// Handles client-server communication, state sync, and matchmaking."

#pragma once"

#include <string>"
#include <vector>"
#include <memory>"
#include <unordered_map>"
#include "ECS.hpp"

namespace Doomnite {"

// MARK: - Network Message Types"

enum class MessageType {"
    Connect,"
    Disconnect,"
    PlayerUpdate,"
    EntityUpdate,"
    InputUpdate,"
    CombatEvent,"
    QuestUpdate,"
    ChatMessage,"
    LobbyUpdate"
};"

// MARK: - Network Message"

struct NetworkMessage {"
    MessageType type;"
    std::string playerId;"
    std::string data;      // JSON or binary data"
    double timestamp;"
    
    NetworkMessage(MessageType msgType = MessageType::ChatMessage,"
                  const std::string& pid = "", const std::string& msgData = "")"
        : type(msgType), playerId(pid), data(msgData),"
          timestamp(0.0) {}  // Would use actual timestamp"
};"

// MARK: - Network Component (ECS) - For multiplayer entities"

struct NetworkComponent : public Component {"
    std::string networkId;"
    bool isLocalPlayer;"
    bool isReplicating;   // Should this entity be synced?"
    float replicationRate; // Updates per second"
    float lastReplicationTime;"
    
    NetworkComponent(const std::string& netId = "", bool local = false)"
        : networkId(netId), isLocalPlayer(local), isReplicating(true),"
          replicationRate(20.0f), lastReplicationTime(0.0f) {}"
    
    bool shouldReplicate(float deltaTime) {"
        lastReplicationTime += deltaTime;"
        if (lastReplicationTime >= 1.0f / replicationRate) {"
            lastReplicationTime = 0.0f;"
            return true;"
        }"
        return false;"
    }"
};"

// MARK: - Lobby Info"

struct LobbyInfo {"
    std::string lobbyId;"
    std::string hostPlayerId;"
    std::vector<std::string> players;"
    int maxPlayers;"
    bool isPublic;"
    std::string gameMode;    // "battle_royale", "coop", etc."
    std::string mapName;"
    
    LobbyInfo(const std::string& id = "", int max = 4)"
        : lobbyId(id), maxPlayers(max), isPublic(true) {}"
    
    bool isFull() const {"
        return static_cast<int>(players.size()) >= maxPlayers;"
    }"
    
    bool addPlayer(const std::string& playerId) {"
        if (isFull()) return false;"
        players.push_back(playerId);"
        return true;"
    }"
    
    bool removePlayer(const std::string& playerId) {"
        auto it = std::find(players.begin(), players.end(), playerId);"
        if (it != players.end()) {"
            players.erase(it);"
            return true;"
        }"
        return false;"
    }"
};"

// MARK: - Client Prediction (for lag compensation)"

struct ClientPrediction {"
    Vec3 lastServerPosition;"
    Vec3 clientPosition;"
    Vec3 predictedPosition;"
    float predictionError;"
    
    ClientPrediction() : lastServerPosition(Vec3Zero),"
                        clientPosition(Vec3Zero),"
                        predictedPosition(Vec3Zero),"
                        predictionError(0.0f) {}"
    
    void updatePrediction(float deltaTime) {"
        // Simple prediction: extrapolate from last known position"
        Vec3 velocity = (clientPosition - lastServerPosition) / deltaTime;"
        predictedPosition = clientPosition + velocity * deltaTime;"
    }"
    
    void reconcile(const Vec3& serverPosition) {"
        lastServerPosition = serverPosition;"
        predictionError = Vec3Distance(clientPosition, serverPosition);"
        "
        // Snap if error too large"
        if (predictionError > 2.0f) {"
            clientPosition = serverPosition;"
        }"
    }"
};"

// MARK: - Network System (ECS System)"

class NetworkSystem : public System {"
private:"
    std::unordered_map<std::string, std::shared_ptr<LobbyInfo>> lobbies;"
    std::string localPlayerId;"
    bool isConnected;"
    float updateInterval;"
    float updateTimer;"
    "
public:"
    NetworkSystem() : isConnected(false), updateInterval(0.05f), updateTimer(0.0f) {}"
    "
    void update(EntityManager& entities, float deltaTime) override {"
        auto networkComponents = entities.componentStorage.getAllComponents<NetworkComponent>();"
        "
        for (auto& pair : networkComponents) {"
            Entity entity = pair.first;"
            auto netComp = pair.second;"
            "
            if (!netComp->isReplicating) continue;"
            "
            // Check if should replicate"
            if (netComp->shouldReplicate(deltaTime)) {"
                // In real implementation:"
                // 1. Serialize entity state (position, rotation, etc.)"
                // 2. Send to server or other clients"
                // 3. Update last replication time inside shouldReplicate"
            }"
        }"
        "
        // Process received messages (would be in a separate thread)"
        processIncomingMessages(entities);"
    }"
    "
    bool connect(const std::string& playerId, const std::string& serverUrl) {"
        // In real implementation: connect to server via WebSocket or TCP"
        localPlayerId = playerId;"
        isConnected = true;"
        return true;"
    }"
    "
    void disconnect() {"
        isConnected = false;"
        localPlayerId.clear();"
    }"
    "
    bool createLobby(const std::string& lobbyId, int maxPlayers = 4) {"
        auto lobby = std::make_shared<LobbyInfo>(lobbyId, maxPlayers);"
        lobby->hostPlayerId = localPlayerId;"
        lobbies[lobbyId] = lobby;"
        return true;"
    }"
    "
    bool joinLobby(const std::string& lobbyId) {"
        auto it = lobbies.find(lobbyId);"
        if (it == lobbies.end()) return false;"
        "
        return it->second->addPlayer(localPlayerId);"
    }"
    "
    void sendMessage(const NetworkMessage& message) {"
        if (!isConnected) return;"
        "
        // In real implementation: serialize and send via network"
    }"
    "
private:"
    void processIncomingMessages(EntityManager& entities) {"
        // Would process messages from server/other clients"
        // Update entity positions, handle combat events, etc."
    }"
};"

// MARK: - Network Manager (Singleton for game-wide access)"

class NetworkManager {"
private:"
    static NetworkManager* instance;"
    std::unique_ptr<NetworkSystem> networkSystem;"
    "
    NetworkManager() : networkSystem(std::make_unique<NetworkSystem>()) {}"
    "
public:"
    static NetworkManager& getInstance() {"
        if (!instance) {"
            instance = new NetworkManager();"
        }"
        return *instance;"
    }"
    "
    NetworkSystem* getNetworkSystem() {"
        return networkSystem.get();"
    }"
    "
    // Delete copy/move"
    NetworkManager(const NetworkManager&) = delete;"
    NetworkManager& operator=(const NetworkManager&) = delete;"
};"

NetworkManager* NetworkManager::instance = nullptr;"

} // namespace Doomnite"
