// DayNightSystem.hpp - C++ Day/Night Cycle for Doomnite"
// FULL Implementation: Real-time day/night with lighting/color changes."

#pragma once"

#include <string>"
#include <vector>"
#include <memory>"
#include "ECS.hpp>"
#include "MathTypes.h>"

namespace Doomnite {"

// MARK: - Time of Day"

enum class TimeOfDay {"
    Dawn,"       // 5:00-7:00"
    Morning,"    // 7:00-12:00"
    Afternoon,"  // 12:00-17:00"
    Dusk,"       // 17:00-19:00"
    Night,"      // 19:00-5:00"
    Midnight"    // Special: 0:00-4:00"
};"

// MARK: - Sky Settings (for rendering)"

struct SkySettings {"
    Vec3 skyColor;"
    Vec3 sunColor;"
    Vec3 ambientColor;"
    float sunIntensity;"
    float ambientIntensity;"
    Vec3 fogColor;"
    float fogDensity;"
    
    SkySettings(const Vec3& sky = Vec3One, const Vec3& sun = Vec3One,"
               const Vec3& ambient = Vec3One, float sunInt = 1.0f,"
               float ambInt = 0.5f, const Vec3& fog = Vec3One,"
               float fogDens = 0.1f)"
        : skyColor(sky), sunColor(sun), ambientColor(ambient),"
          sunIntensity(sunInt), ambientIntensity(ambInt),"
          fogColor(fog), fogDensity(fogDens) {}
};"

// MARK: - Day/Night Component (ECS)"

struct DayNightComponent : public Component {"
    float currentTime;"        // In seconds (0-86400 = 24h)"
    float timeScale;"          // 1.0 = real time, 60.0 = 1min = 1 game hour"
    bool isPaused;"
    TimeOfDay currentPeriod;"
    float sunriseTime;"       // 5:00 = 18000s"
    float sunsetTime;"        // 19:00 = 68400s"
    bool affectsLighting;"     // Does it change scene lighting?"
    bool affectsMonsters;"    // Do monsters change behavior?"
    bool affectsMusic;"        // Does music change?"
    
    DayNightComponent(float scale = 60.0f)"
        : currentTime(18000.0f), timeScale(scale), isPaused(false),"
          currentPeriod(TimeOfDay::Morning),"
          sunriseTime(18000.0f), sunsetTime(68400.0f),"
          affectsLighting(true), affectsMonsters(true), affectsMusic(true) {}
    
    TimeOfDay getTimeOfDay() const {"
        float hours = (currentTime / 3600.0f);"
        if (hours >= 5.0f && hours < 7.0f) return TimeOfDay::Dawn;"
        if (hours >= 7.0f && hours < 12.0f) return TimeOfDay::Morning;"
        if (hours >= 12.0f && hours < 17.0f) return TimeOfDay::Afternoon;"
        if (hours >= 17.0f && hours < 19.0f) return TimeOfDay::Dusk;"
        if (hours >= 19.0f || hours < 5.0f) return TimeOfDay::Night;"
        return TimeOfDay::Morning;"  // Fallback"
    }
    
    float getTimeOfDayNormalized() const {"
        return currentTime / 86400.0f;"  // 0.0-1.0"
    }
    
    std::string getTimeString() const {"
        int totalSeconds = static_cast<int>(currentTime);"
        int hours = (totalSeconds / 3600) % 24;"
        int minutes = (totalSeconds % 3600) / 60;"
        "
        char buffer[10];"
        snprintf(buffer, sizeof(buffer), "%02d:%02d", hours, minutes);"
        return std::string(buffer);"
    }
    
    bool isNight() const {"
        TimeOfDay tod = getTimeOfDay();"
        return tod == TimeOfDay::Night || tod == TimeOfDay::Dusk;"
    }
    
    void update(float deltaTime) {"
        if (isPaused) return;"
        
        currentTime += deltaTime * timeScale;"
        if (currentTime >= 86400.0f) {"
            currentTime -= 86400.0f;"  // Wrap around"
        }
        
        TimeOfDay newPeriod = getTimeOfDay();"
        if (newPeriod != currentPeriod) {"
            currentPeriod = newPeriod;"
            // Would trigger zone/monster/music changes"
        }
    }
};"

// MARK: - Predefined Sky Settings for Time Periods"

namespace DayNightSettings {"
    "
    static SkySettings DAWN_SKY("
        Vec3(0.8f, 0.6f, 0.9f),   // Purple-ish"
        Vec3(1.0f, 0.7f, 0.5f),   // Warm sunrise"
        Vec3(0.3f, 0.3f, 0.4f),"
        0.7f, 0.2f,"
        Vec3(0.6f, 0.5f, 0.7f), 0.05f"
    );"
    
    static SkySettings MORNING_SKY("
        Vec3(0.5f, 0.7f, 1.0f),   // Clear blue"
        Vec3(1.0f, 1.0f, 0.9f),   // Bright sun"
        Vec3(0.5f, 0.5f, 0.5f),"
        1.0f, 0.5f,"
        Vec3(0.8f, 0.8f, 0.8f), 0.1f"
    );"
    
    static SkySettings AFTERNOON_SKY("
        Vec3(0.6f, 0.8f, 1.0f),   // Slightly warmer"
        Vec3(1.0f, 0.95f, 0.8f),"
        Vec3(0.6f, 0.6f, 0.5f),"
        0.9f, 0.5f,"
        Vec3(0.7f, 0.7f, 0.6f), 0.15f"
    );"
    
    static SkySettings DUSK_SKY("
        Vec3(0.9f, 0.5f, 0.3f),   // Orange/red"
        Vec3(1.0f, 0.6f, 0.3f),   // Warm sunset"
        Vec3(0.4f, 0.3f, 0.3f),"
        0.6f, 0.3f,"
        Vec3(0.5f, 0.4f, 0.4f), 0.2f"
    );"
    
    static SkySettings NIGHT_SKY("
        Vec3(0.1f, 0.1f, 0.2f),   // Dark blue"
        Vec3(0.3f, 0.3f, 0.5f),   // Moonlight"
        Vec3(0.1f, 0.1f, 0.15f),"
        0.2f, 0.1f,"
        Vec3(0.05f, 0.05f, 0.1f), 0.3f"
    );"
    "
    static const SkySettings* getSettingsForTime(TimeOfDay tod) {"
        switch (tod) {"
            case TimeOfDay::Dawn: return &DAWN_SKY;"
            case TimeOfDay::Morning: return &MORNING_SKY;"
            case TimeOfDay::Afternoon: return &AFTERNOON_SKY;"
            case TimeOfDay::Dusk: return &DUSK_SKY;"
            case TimeOfDay::Night: return &NIGHT_SKY;"
            case TimeOfDay::Midnight: return &NIGHT_SKY;"
            default: return &MORNING_SKY;"
        }"
    }"
}"

// MARK: - Day/Night System (ECS System)"

class DayNightSystem : public System {"
private:"
    std::vector<DayNightComponent*> activeDayNight;"
    
public:"
    void update(EntityManager& entities, float deltaTime) override {"
        auto dayNightComponents = entities.componentStorage.getAllComponents<DayNightComponent>();"
        "
        for (auto& pair : dayNightComponents) {"
            Entity entity = pair.first;"
            auto dayNight = pair.second;"
            "
            // Update time"
            dayNight->update(deltaTime);"
            "
            // Apply effects if this is the main world controller"
            if (dayNight->affectsLighting) {"
                applyLightingEffects(*dayNight, entities);"
            }"
            "
            if (dayNight->affectsMonsters) {"
                applyMonsterEffects(*dayNight, entities);"
            }"
            "
            if (dayNight->affectsMusic) {"
                applyMusicEffects(*dayNight, entities);"
            }"
            "
            // Update back in storage"
            entities.componentStorage.addComponent<DayNightComponent>(entity, dayNight);"
        }"
    }"
    "
private:"
    void applyLightingEffects(const DayNightComponent& dayNight, EntityManager& entities) {"
        auto* skySettings = DayNightSettings::getSettingsForTime(dayNight.currentTimeOfDay());"
        if (!skySettings) return;"
        "
        // In real implementation: update scene lighting"
        // 1. Set ambient light color"
        // 2. Set directional light (sun/moon) color/intensity"
        // 3. Update fog color/density"
        // 4. Notify rendering system"
    }"
    "
    void applyMonsterEffects(const DayNightComponent& dayNight, EntityManager& entities) {"
        if (!dayNight.isNight()) return;"
        "
        // Night: monsters are more aggressive"
        // Would modify AI components:"
        // - Increase detection radius"
        // - Increase damage"
        // - Change active monsters (more nocturnal)"
        "
        auto enemies = entities.componentStorage.getAllComponents<EnemyAIComponent>();"
        for (auto& pair : enemies) {"
            if (dayNight.isNight()) {"
                // Boost night enemies"
                // pair.second->detectionRadius *= 1.5f;"
            }"
        }"
    }"
    "
    void applyMusicEffects(const DayNightComponent& dayNight, EntityManager& entities) {"
        // Change ambient music based on time of day"
        // Would call AudioSystem to crossfade music tracks"
        "
        TimeOfDay tod = dayNight.currentTimeOfDay();"
        std::string musicId;"
        "
        switch (tod) {"
            case TimeOfDay::Dawn:"
            case TimeOfDay::Dusk:"
                musicId = "music_transition";"
                break;"
            case TimeOfDay::Night:"
                musicId = "music_night";"
                break;"
            default:"
                musicId = "music_day";"
                break;"
        }"
        "
        // Would trigger music change via AudioSystem"
    }"
};"

} // namespace Doomnite"
