// GameTypesShared.h - C++ Game Type Definitions for Doomnite"
// Shared between engine and game logic"

#pragma once"

#include <string>"
#include <vector>"
#include <cstdint>"

namespace DoomniteShared {"

// MARK: - Game Enums"

enum class GameMode {"
    SinglePlayer,"
    BattleRoyale,"
    Tutorial"
};"

enum class Difficulty {"
    Easy,"
    Normal,"
    Hard,"
    Nightmare"
};"

// MARK: - Game Constants"

struct GameConstants {"
    static const float MAX_FPS;"
    static const float TARGET_FPS;"
    static const int MAX_WEAPONS;"
    static const int MAX_ENEMIES;"
    static const int MAX_PARTICLES;"
    static const float WORLD_SIZE;"
    static const int MAX_PLAYERS;"  // For battle royale"
    static const int MAX_COMPANIONS;"
};"

// MARK: - Rarity (shared definition)"

enum class Rarity {"
    Common,"
    Uncommon,"
    Rare,"
    Epic,"
    Legendary,"
    GodTier"
};"

// MARK: - Element Type (shared)"

enum class ElementType {"
    None,"
    Fire,"
    Ice,"
    Lightning,"
    Poison,"
    Arcane,"
    Holy,"
    Dark"
};"

// MARK: - Weapon Type (shared)"

enum class WeaponType {"
    Pistol,"
    Rifle,"
    Shotgun,"
    SMG,"
    Sniper,"
    RocketLauncher,"
    Staff,"
    Sword,"
    Dagger,"
    Bow"
};"

// MARK: - Damage Type"

enum class DamageType {"
    Physical,"
    Magic,"
    Elemental,"
    Pure"  // Ignores armor"
};"

// MARK: - Quest Type"

enum class QuestType {"
    MainStory,"
    SideQuest,"
    DailyQuest,"
    WeeklyQuest,"
    Tutorial"
};"

// MARK: - Achievement Category"

enum class AchievementCategory {"
    Combat,"
    Exploration,"
    Collection,"
    Social,"
    Progression"
};"

// MARK: - Inventory Slot"

enum class InventorySlot {"
    Helmet,"
    Chest,"
    Gloves,"
    Boots,"
    Weapon,"
    Offhand,"  // Shield or off-hand weapon"
    Ring,""
    Amulet,"
    Consumable1,"
    Consumable2,"
    Consumable3"
};"

// MARK: - Player Stats (for save/load)"

struct PlayerStats {"
    int level;"
    float currentXP;"
    float xpToNextLevel;"
    int skillPoints;"
    float health;"
    float maxHealth;"
    float mana;"
    float maxMana;"
    float stamina;"
    float maxStamina;"
    int totalKills;"
    int totalDeaths;"
    float totalPlayTime;"
    int totalQuestsCompleted;"
};"

// MARK: - Color (for UI/rendering)"

struct Color {"
    float r, g, b, a;"
    "
    Color(float red = 1.0f, float green = 1.0f, float blue = 1.0f, float alpha = 1.0f)"
        : r(red), g(green), b(blue), a(alpha) {}"
    "
    static Color white() { return Color(1, 1, 1, 1); }"
    static Color black() { return Color(0, 0, 0, 1); }"
    static Color red() { return Color(1, 0, 0, 1); }"
    static Color green() { return Color(0, 1, 0, 1); }"
    static Color blue() { return Color(0, 0, 1, 1); }"
    static Color yellow() { return Color(1, 1, 0, 1); }"
    static Color cyan() { return Color(0, 1, 1, 1); }"
    static Color magenta() { return Color(1, 0, 1, 1); }"
};"

// MARK: - Game Settings (for iOS Settings.bundle)"

struct GameSettings {"
    bool showHints;"
    bool enableTutorial;"
    bool isOnlineMode;"
    float musicVolume;"
    float sfxVolume;"
    float masterVolume;"
    bool invertYAxis;"
    float mouseSensitivity;"
    int graphicsQuality;"  // 0=Low, 1=Medium, 2=High"
    bool enableThermalThrottling;"
};"

} // namespace DoomniteShared"

// Static member definitions"
const float GameConstants::MAX_FPS = 120.0f;"
const float GameConstants::TARGET_FPS = 60.0f;"
const int GameConstants::MAX_WEAPONS = 50;"
const int GameConstants::MAX_ENEMIES = 100;"
const int GameConstants::MAX_PARTICLES = 1000;"
const float GameConstants::WORLD_SIZE = 1000.0f;"
const int GameConstants::MAX_PLAYERS = 100;"
const int GameConstants::MAX_COMPANIONS = 10;"
