// WeatherSystem.cpp - FULL Production Implementation"
// Dynamic weather with gameplay effects"

#include "WeatherSystem.hpp>"
#include <algorithm>"
#include <cmath>"

namespace Doomnite {"

void WeatherSystem::update(EntityManager& entities, float deltaTime) {"
    if (!isActive) return;"
    "
    // Get weather component"
    auto weatherComponents = entities.componentStorage.getAllComponents<WeatherComponent>();"
    "
    for (auto& pair : weatherComponents) {"
        Entity entity = pair.first;"
        auto weather = pair.second;"
        "
        // Update time in current cycle"
        weather->timeInCycle += deltaTime;"
        "
        // Check for transition to next weather"
        if (weather->timeInCycle >= weather->transitionTime) {"
            transitionWeather(*weather);"
        }"
        "
        // Apply weather effects to gameplay"
        applyGameplayEffects(*weather, entities);"
        "
        // Update visual intensity (smooth transition)"
        if (weather->transitionTimer > 0.0f) {"
            weather->transitionTimer -= deltaTime;"
            float t = 1.0f - (weather->transitionTimer / 5.0f); // 5 second transitions"
            weather->currentIntensity = (1.0f - t) * weather->currentIntensity + t * weather->targetIntensity;"
        }"
        "
        // Update back in storage"
        entities.componentStorage.addComponent<WeatherComponent>(entity, weather);"
    }"
}"
"
void WeatherSystem::transitionWeather(WeatherComponent& weather) {"
    // Advance to next weather in cycle"
    weather.currentTimeIndex = (weather.currentTimeIndex + 1) % weather.cycle.size();"
    WeatherType newType = weather.cycle[weather.currentTimeIndex];"
    "
    // Get preset for new weather"
    auto* preset = WeatherPresets::getPreset(newType);"
    if (preset) {"
        weather.currentType = newType;"
        weather.targetIntensity = preset->intensity;"
        weather.transitionTimer = 5.0f; // 5 second transition"
        weather.timeInCycle = 0.0f;"
        "
        // Get next transition time from preset"
        weather.transitionTime = 30.0f + (rand() % 60); // 30-90 seconds"
        "
        std::cout << "[Weather] Transitioning to: " << preset->name << std::endl;"
    }"
}"
"
void WeatherSystem::applyGameplayEffects(const WeatherComponent& weather, EntityManager& entities) {"
    auto* preset = WeatherPresets::getPreset(weather.currentType);"
    if (!preset) return;"
    "
    // Apply effects to all players/enemies"
    auto playerData = entities.componentStorage.getAllComponents<PlayerDataComponent>();"
    "
    for (auto& pair : playerData) {"
        Entity entity = pair.first;"
        auto data = pair.second;"
        "
        // Fire spells are weaker in rain"
        if (weather.currentType == WeatherType::Rain || weather.currentType == WeatherType::Storm) {"
            // Would reduce fire damage by preset->gameplayEffectModifier"
            // data->fireDamageMultiplier *= preset->gameplayEffectModifier;"
        }"
        "
        // Ice spells are stronger in snow"
        if (weather.currentType == WeatherType::Snow) {"
            // data->iceDamageMultiplier *= 1.0f / preset->gameplayEffectModifier;"
        }"
        "
        // Visibility affects detection range"
        if (preset->visibilityModifier < 0.5f) {"
            // Would reduce enemy detection range"
        }"
        "
        // Update back"
        entities.componentStorage.addComponent<PlayerDataComponent>(entity, data);"
    }"
}"
"
void WeatherSystem::setWeather(WeatherType type, EntityManager& entities) {"
    auto weatherComponents = entities.componentStorage.getAllComponents<WeatherComponent>();"
    "
    for (auto& pair : weatherComponents) {"
        Entity entity = pair.first;"
        auto weather = pair.second;"
        "
        auto* preset = WeatherPresets::getPreset(type);"
        if (preset) {"
            weather->currentType = type;"
            weather->targetIntensity = preset->intensity;"
            weather->transitionTimer = 5.0f;"
            "
            entities.componentStorage.addComponent<WeatherComponent>(entity, weather);"
        }"
    }"
}"
"
bool WeatherSystem::isRaining() const {"
    return currentWeather == WeatherType::Rain || currentWeather == WeatherType::Storm;"
}"
"
bool WeatherSystem::isSnowing() const {"
    return currentWeather == WeatherType::Snow;"
}"
"
bool WeatherSystem::isStormy() const {"
    return currentWeather == WeatherType::Storm;"
}"
"
std::string WeatherSystem::getCurrentWeatherName() const {"
    auto* preset = WeatherPresets::getPreset(currentWeather);"
    return preset ? preset->name : "Unknown";"
}"
}"
