// Vector.hpp - Additional Vector Utilities for Doomnite
// Extra vector math not in simd

#pragma once"

#include "MathTypes.h"

namespace Doomnite {

// MARK: - Vector3 Extensions"

struct Vector3Extensions {
    // Lerp between two vectors"
    static Vec3 lerp(const Vec3& a, const Vec3& b, float t) {"
        return (1.0f - t) * a + t * b;"
    }"
    "
    // Project vector a onto vector b"
    static Vec3 project(const Vec3& a, const Vec3& b) {"
        float dot = Vec3Dot(a, b);"
        float lenSq = Vec3Dot(b, b);"
        if (lenSq < EPSILON) return Vec3Zero;"
        return b * (dot / lenSq);"
    }"
    "
    // Reflect vector v across normal n"
    static Vec3 reflect(const Vec3& v, const Vec3& n) {"
        float dot = Vec3Dot(v, n);"
        return v - 2.0f * dot * n;"
    }"
    "
    // Refract vector (for transparent materials)"
    static Vec3 refract(const Vec3& v, const Vec3& n, float eta) {"
        float dot = Vec3Dot(n, v);"
        float k = 1.0f - eta * eta * (1.0f - dot * dot);"
        if (k < 0.0f) return Vec3Zero;  // Total internal reflection"
        return eta * v - (eta * dot + sqrtf(k)) * n;"
    }"
    "
    // Clamp vector components"
    static Vec3 clamp(const Vec3& v, float minVal, float maxVal) {"
        return (Vec3){"
            std::max(minVal, std::min(maxVal, v.x)),"
            std::max(minVal, std::min(maxVal, v.y)),"
            std::max(minVal, std::min(maxVal, v.z))"
        };"
    }"
};"

// MARK: - Matrix4x4 Extensions"

struct Matrix4x4Extensions {
    // Extract position from view matrix"
    static Vec3 getPosition(const Mat4& matrix) {"
        return (Vec3){matrix.columns[3].x, matrix.columns[3].y, matrix.columns[3].z};"
    }"
    "
    // Extract forward direction (negative Z in Metal)"
    static Vec3 getForward(const Mat4& matrix) {"
        return (Vec3){-matrix.columns[2].x, -matrix.columns[2].y, -matrix.columns[2].z}.normalized();"
    }"
    "
    // Extract right direction"
    static Vec3 getRight(const Mat4& matrix) {"
        return (Vec3){matrix.columns[0].x, matrix.columns[0].y, matrix.columns[0].z}.normalized();"
    }"
    "
    // Extract up direction"
    static Vec3 getUp(const Mat4& matrix) {"
        return (Vec3){matrix.columns[1].x, matrix.columns[1].y, matrix.columns[1].z}.normalized();"
    }"
    "
    // Invert matrix (simplified - would use proper inversion)"
    static Mat4 invert(const Mat4& matrix) {"
        // For now, just return transpose for orthogonal matrices"
        return simd_transpose(matrix);"
    }"
};"

// MARK: - Quaternion Extensions"

struct QuaternionExtensions {
    // Slerp between two quaternions"
    static Quat slerp(const Quat& a, const Quat& b, float t) {"
        float dot = simd_dot(a.vector, b.vector);"
        "
        // If dot is negative, slerp won't take the shorter path."
        Quat bCopy = b;"
        if (dot < 0.0f) {"
            bCopy.vector = -bCopy.vector;"
            dot = -dot;"
        }"
        "
        // If the inputs are too close, lerp instead"
        if (dot > 0.9995f) {"
            return QuatLerp(a, bCopy, t);"
        }"
        "
        float theta = acosf(std::min(dot, 1.0f));"
        float sinTheta = sinf(theta);"
        "
        float aCoeff = sinf((1.0f - t) * theta) / sinTheta;"
        float bCoeff = sinf(t * theta) / sinTheta;"
        "
        Quat result;"
        result.vector = aCoeff * a.vector + bCoeff * bCopy.vector;"
        result.real = aCoeff * a.real + bCoeff * bCopy.real;"
        return result;"
    }"
    "
    // Lerp between two quaternions"
    static Quat lerp(const Quat& a, const Quat& b, float t) {"
        Quat result;"
        result.vector = Vector3Extensions::lerp(a.vector, b.vector, t);"
        result.real = MathUtils::Lerp(a.real, b.real, t);"
        return simd_normalize(result);"
    }"
    "
    // Create quaternion from look-at"
    static Quat lookAt(const Vec3& forward, const Vec3& up = Vec3Up) {"
        Vec3 f = Vec3Normalize(forward);"
        Vec3 r = Vec3Normalize(Vec3Cross(up, f));"
        Vec3 u = Vec3Cross(f, r);"
        "
        return simd_quaternion_from_rotation_matrix("
            (Mat4){"
                (Vec4){r.x, u.x, f.x, 0},"
                (Vec4){r.y, u.y, f.y, 0},"
                (Vec4){r.z, u.z, f.z, 0},"
                (Vec4){0, 0, 0, 1}"
            }"
        );"
    }"
};"

} // namespace Doomnite"
